/// Stable identities for shared activation allowances, independent of feedback names.
/// Keep distinct mechanics separate even when their displayed Talent names match.
package enum CombatActivationClaim: Hashable, Sendable {
    case aetherShield
    case aetherialSurge
    case alphaHowl
    case alphaStrike
    case arcaneReservoir
    case arcaneSurge
    case ashenArsenal
    case basicAttackFreezeBuildup
    case batteringRam
    case belowHalfGoldGainHeal
    case blazingFeathers
    case bleedCriticalDraw
    case bloodfire
    case boneShield
    case burnAttackDoubleChance
    case burnCriticalMana
    case carnivore
    case cheerUp
    case chillingScales
    case clearSolution
    case consolationPrize
    case criticalActionGold
    case criticalGoldTheftDraw
    case crownfall
    case cutpurseCut
    case darkRecovery
    case dazingSwipe
    case dispelMagic
    case divineBlessing
    case dragonSpark
    case endlessLegion
    case evasivePack
    case faeWard
    case feintStrike
    case feralFrenzy
    case fetch
    case firstGoldTheftDouble
    case firstGoldTheftDraw
    case firstGoldTheftHeal
    case flameShield
    case fontOfMagic
    case goldGainDrawChance
    case goldGainPartyHeal
    case goldGainThresholdDraw
    case goldTheftChanceDraw
    case grizzlyGuard
    case groundSlam
    case groveAccord
    case guardian
    case healingFlames
    case healthRestorationRolls
    case hoardArmor
    case jackpot
    case lightFingered
    case lingeringBlessing
    case livingArchive
    case loyalCompanion
    case luckyStrike
    case manaFlow
    case marrowmend
    case massCleanse
    case overhealFirstBlock
    case packBloodlust
    case paralysis
    case playfulEnergy
    case prismaticEdge
    case prismaticSpark
    case purifyingLight
    case purifyingWisdom
    case quakingCarapace
    case radiantBarrier
    case radiantShell
    case radiantWisdom
    case redline
    case sealedVial
    case seismicRoar
    case shieldBond
    case snatch
    case soulSharing
    case spendOvercharge
    case spitefulHeal
    case spriteTouch
    case stolenBreath
    case stolenThunder
    case sunGlyph
    case sunlightSpark
    case sunwall
    case surpriseStrike
    case tailwind
    case unstableCulture
    case vitalInfusion
    case wildcardGoldGain
}
