import SwiftUI

enum DesignAssetColors {
    static func named(_ name: String) -> Color {
        Color(name, bundle: .module)
    }

    static let allCatalogAssetNames: [String] = [
        "BattleSliceCrack",
        "BattleSliceSpark",
        "ChapterDesert",
        "ChapterDungeon",
        "ChapterForest",
        "ChapterTundra",
        "EncounterBattle",
        "EncounterEvent",
        "EncounterShop",
        "KeywordBleed",
        "KeywordBlock",
        "KeywordBurn",
        "KeywordCleanse",
        "KeywordDeathsDoor",
        "KeywordDodge",
        "KeywordFreeze",
        "KeywordHealth",
        "KeywordHoly",
        "KeywordLeech",
        "KeywordMana",
        "KeywordPhysical",
        "KeywordPoison",
        "KeywordPurge",
        "KeywordStun",
        "KeywordThorns",
        "PlaceholderAbility",
        "PlaceholderCompanion",
        "PlaceholderEnemy",
        "PlaceholderHero",
        "PlaceholderItem",
        "ResourceCrystal",
        "ResourceFood",
        "ResourceHerbs",
        "ResourceHide",
        "ResourceIron",
        "ResourceStone",
        "ResourceWood",
        "ThemeAntiqueGold",
        "ThemeArcane",
        "ThemeCanvas",
        "ThemeDestructive",
        "ThemeElevated",
        "ThemeHealth",
        "ThemeHealthRestore",
        "ThemeHighlightGold",
        "ThemeInformational",
        "ThemeOverlayInk",
        "ThemeOverlayPaper",
        "ThemePanel",
        "ThemePressedGold",
        "ThemeSubtleStroke",
        "ThemeSuccess",
        "ThemeSurface",
        "ThemeWarning",
    ]
}
