#!/usr/bin/env bash
set -euo pipefail
ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
source "$ROOT_DIR/Scripts/lib/media-assets.sh"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

printf '# Generated by fixture\n# asset_name\tsource_sha256\nalpha\taaa\nzulu\tbbb\n' > "$TMP_DIR/expected"
for locale in C en_US.UTF-8; do
  printf '# Generated by fixture\n# asset_name\tsource_sha256\nzulu\tbbb\nalpha\taaa\n' > "$TMP_DIR/input"
  LC_ALL="$locale" trinket_asset_sort_state "$TMP_DIR/input" "$TMP_DIR/output"
  cmp "$TMP_DIR/expected" "$TMP_DIR/output"
  touch -t 200001010000 "$TMP_DIR/output"
  cp -p "$TMP_DIR/output" "$TMP_DIR/before"
  cp "$TMP_DIR/output" "$TMP_DIR/input"
  LC_ALL="$locale" trinket_asset_sort_state "$TMP_DIR/input" "$TMP_DIR/output"
  [[ ! "$TMP_DIR/output" -nt "$TMP_DIR/before" ]]
  [[ ! -e "$TMP_DIR/input" ]]
done
echo "asset-hash locale regressions passed"
