#!/usr/bin/env bash
set -euo pipefail

# Regression: asset hash TSV writers must keep headers stable under en_US collation.
ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
source "$ROOT_DIR/Scripts/lib/xcodebuild-infra.sh"

TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

input="$TMP_DIR/hashes.tsv"
cat > "$input" <<'EOF'
# Generated by Scripts/prepare-music-assets.sh. Do not edit directly.
# asset_name	source_sha256
music_zulu	aaa
music_alpha	bbb
EOF

sort_hash_tsv() {
  local src="$1"
  local dest="$2"
  {
    head -n 2 "$src"
    tail -n +3 "$src" | LC_ALL=C sort -t$'\t' -k1,1
  } > "$dest"
}

# Plain locale-sensitive sort reorders the two comment headers under en_US.
LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 sort "$input" > "$TMP_DIR/naive-en.tsv"
if head -n 1 "$TMP_DIR/naive-en.tsv" | grep -q 'Generated by'; then
  echo "unexpected: en_US naive sort kept Generated-by first (locale may match C)" >&2
else
  echo "confirmed: en_US naive sort reorders hash TSV headers"
fi

sort_hash_tsv "$input" "$TMP_DIR/stable-c.tsv"
LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 bash -c '
  {
    head -n 2 "$1"
    tail -n +3 "$1" | LC_ALL=C sort -t$'\''\t'\'' -k1,1
  } > "$2"
' _ "$input" "$TMP_DIR/stable-en.tsv"

cmp -s "$TMP_DIR/stable-c.tsv" "$TMP_DIR/stable-en.tsv"
head -n 1 "$TMP_DIR/stable-en.tsv" | grep -q 'Generated by'
grep -q 'music_alpha' "$TMP_DIR/stable-en.tsv"

# Prepare scripts must use header-preserving C sort (not whole-file locale sort).
for script in \
  prepare-app-icon.sh \
  prepare-music-assets.sh \
  prepare-sfx-assets.sh \
  prepare-cinematic-assets.sh \
  prepare-art-assets.sh
do
  path="$ROOT_DIR/Scripts/$script"
  grep -q 'LC_ALL=C sort' "$path"
  grep -Eq 'head -n 2|tail -n \+3' "$path"
done

# Infra retry matcher covers XCUITest launch flakes even when exit is 65.
launch_log="$TMP_DIR/launch.log"
cat > "$launch_log" <<'EOF'
Failed to launch <XCUIApplicationImpl: 0x1 com.ryanmcintire.Trinket> via Xcode: Timed out while launching application via Xcode.
Failed to get background assertion for target app with pid 18060: No failure details provided
EOF
trinket_xcodebuild_log_is_infrastructure_failure 65 "$launch_log"
! trinket_xcodebuild_log_is_infrastructure_failure 65 "$TMP_DIR/missing.log"
product_log="$TMP_DIR/product.log"
echo 'XCTAssertEqual failed: ("1") is not equal to ("2")' > "$product_log"
! trinket_xcodebuild_log_is_infrastructure_failure 65 "$product_log"
trinket_xcodebuild_log_is_infrastructure_failure 70 "$product_log"

echo "asset-hash locale + xcode infra retry regressions passed."
