from __future__ import annotations

from pathlib import Path
from unittest.mock import patch
import tempfile

from script_test_support import ScriptRegressionTestCase
from internal.content import common


class CodegenCommonTests(ScriptRegressionTestCase):
    def test_generated_files_carry_explicit_access_control(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "Sample.generated.swift"
            common.write_generated_file(path, "public extension Ability {\n}\n")
            text = path.read_text(encoding="utf-8")
            self.assertTrue(text.startswith("// Generated by Scripts/content_codegen.py"))
            self.assertIn("public extension Ability {", text)

            internal = Path(directory) / "Catalog.generated.swift"
            common.write_generated_file(internal, "enum ItemAffixCatalogGenerated {\n}\n")
            internal_text = internal.read_text(encoding="utf-8")
            self.assertIn("enum ItemAffixCatalogGenerated {", internal_text)
            self.assertNotIn("public enum", internal_text)

    def test_manifest_table_rejects_ragged_rows(self) -> None:
        with tempfile.NamedTemporaryFile("w", suffix=".tsv", delete=False) as f:
            f.write("# id\tasset_name\n")
            f.write("only_one_column\n")
            temp_path = Path(f.name)
        try:
            with self.assertRaises(ValueError):
                common.read_manifest_table(temp_path)
        finally:
            temp_path.unlink(missing_ok=True)

    def test_parse_tsv_rows_pads_optional_columns_and_enforces_min_columns(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            tsv_path = Path(directory) / "test.tsv"
            tsv_path.write_text("id\tname\topt1\topt2\nitem1\tItem One\n", encoding="utf-8")
            from dataclasses import dataclass

            @dataclass
            class DummyRow:
                id: str
                name: str
                opt1: str
                opt2: str

            rows = common._parse_tsv_rows(tsv_path, ["id", "name", "opt1", "opt2"], DummyRow, min_columns=2)
            self.assertEqual(len(rows), 1)
            self.assertEqual(rows[0].id, "item1")
            self.assertEqual(rows[0].opt1, "")
            self.assertEqual(rows[0].opt2, "")

            with self.assertRaises(ValueError):
                common._parse_tsv_rows(tsv_path, ["id", "name", "opt1", "opt2"], DummyRow, min_columns=3)

    def test_swift_escape_handles_quotes_backslashes_and_newlines(self) -> None:
        self.assertEqual(common.swift_escape("plain"), "plain")
        self.assertEqual(common.swift_escape('say "hi"'), 'say \\"hi\\"')
        self.assertEqual(common.swift_escape("deal {n} damage"), "deal {n} damage")
        self.assertEqual(common.swift_escape("a\\b"), "a\\\\b")
        self.assertEqual(
            common.swift_escape("Increase X by 1\\nProduces 1 Hide per day"),
            "Increase X by 1\\nProduces 1 Hide per day",
        )

    def test_write_if_changed_skips_rewrite_when_identical(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "Sample.generated.swift"
            common.write_if_changed(path, "content\n")
            self.assertEqual(path.read_text(encoding="utf-8"), "content\n")
            with patch.object(Path, "write_text") as writer:
                common.write_if_changed(path, "content\n")
        writer.assert_not_called()
