#!/usr/bin/env python3

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import unittest
from unittest.mock import patch
from pathlib import Path

from script_test_support import ROOT, ScriptRegressionTestCase, load_script

class ContentAndPolicyScriptTests(ScriptRegressionTestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.codegen = load_script("content_codegen", "content_codegen.py")

    def test_shell_policy_checks_reject_search_errors(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            fake_rg = Path(directory) / "rg"
            fake_rg.write_text('#!/bin/sh\nexit "$SEARCH_STATUS"\n')
            fake_rg.chmod(0o755)
            for name in ("api-bans", "agent-invariants", "comment-ban", "exclusivity-footguns", "module-boundaries"):
                for status in (1, 2):
                    with self.subTest(check=name, status=status):
                        result = subprocess.run(
                            [str(ROOT / f"Scripts/check-{name}.sh")], cwd=ROOT,
                            env={**os.environ, "PATH": f"{directory}:{os.environ['PATH']}", "SEARCH_STATUS": str(status)},
                            capture_output=True, text=True,
                        )
                        self.assertEqual(result.returncode, 0 if status == 1 else 2, result.stdout + result.stderr)

    def test_generated_files_carry_explicit_access_control(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "Sample.generated.swift"
            self.codegen.write_generated_file(path, "public extension Ability {\n}\n")
            text = path.read_text(encoding="utf-8")
            self.assertTrue(text.startswith("// Generated by Scripts/content_codegen.py"))
            self.assertIn("public extension Ability {", text)

            internal = Path(directory) / "Catalog.generated.swift"
            self.codegen.write_generated_file(internal, "enum ItemAffixCatalogGenerated {\n}\n")
            internal_text = internal.read_text(encoding="utf-8")
            self.assertIn("enum ItemAffixCatalogGenerated {", internal_text)
            self.assertNotIn("public enum", internal_text)

    def test_homestead_prerequisite_tier_must_exist(self) -> None:
        with self.assertRaises(ValueError):
            self.codegen.validate_homestead_prerequisites(
                "wheatField:9", "orchard-tier-1", {"wheatField": {1, 2}}
            )

    def test_content_codegen_rejects_unknown_command(self) -> None:
        result = subprocess.run(
            [sys.executable, str(ROOT / "Scripts" / "content_codegen.py"), "typo"],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertNotEqual(result.returncode, 0)
        self.assertIn("Unknown command", result.stderr)

    def test_triggers_swift_maps_known_token_to_grouped_field(self) -> None:
        self.assertEqual(
            self.codegen.triggers_swift("on_cleanse_self_heal:2"),
            "CombatTraitTriggers(healing: HealingTriggers(cleanseSelfHeal: 2))",
        )

    def test_triggers_swift_rename_table_tokens(self) -> None:
        output = self.codegen.triggers_swift("on_cleanse_draw:1|on_gain_gold_heal:3")
        self.assertIn("cleanseBonusDraw: 1", output)
        self.assertIn("gainGoldBonusHealSelf: 3", output)

    def test_triggers_swift_damage_below_health_percent_both_arities(self) -> None:
        self.assertEqual(
            self.codegen.triggers_swift("damage_below_health_percent:50:5"),
            "CombatTraitTriggers(damage: DamageTriggers("
            "damageBelowHealthPercentThreshold: 50, damageBelowHealthPercentBonus: 5))",
        )
        self.assertEqual(
            self.codegen.triggers_swift("damage_below_health_percent:50:burn:5"),
            "CombatTraitTriggers(damage: DamageTriggers("
            "damageBelowHealthPercentThreshold: 50, damageBelowHealthPercentKeyword: .burn, "
            "damageBelowHealthPercentBonus: 5))",
        )

    def test_triggers_swift_generic_path_converts_snake_case_field(self) -> None:
        self.assertEqual(
            self.codegen.triggers_swift("poison_decay_slow_percent:50"),
            "CombatTraitTriggers(dot: DotTriggers(poisonDecaySlowPercent: 50))",
        )

    def test_triggers_swift_unknown_token_fails_loudly(self) -> None:
        with self.assertRaises(ValueError):
            self.codegen.triggers_swift("not_a_real_trigger:1")

    def test_triggers_swift_rejects_glued_tokens(self) -> None:
        with self.assertRaises(ValueError):
            self.codegen.triggers_swift("poison_decay_slow_percent:50,bogus_field:1")

    def test_triggers_swift_rejects_duplicate_fields(self) -> None:
        for tokens in (
            "block_per_turn:1|block_per_turn:2",
            "cards_played_mana:2:3|cards_played_mana:4:5",
            "on_cleanse_draw:1|cleanseBonusDraw:2",
            "on_cleanse_draw:1|cleanse_bonus_draw:2",
            "cards_played_mana:2:3|cardsPlayedManaFlat:4",
        ):
            for value in (tokens, "|".join(reversed(tokens.split("|")))):
                with self.subTest(value=value), self.assertRaisesRegex(ValueError, "Duplicate trigger field"):
                    self.codegen.triggers_swift(value)

    def test_triggers_swift_rejects_badly_typed_values(self) -> None:
        for token in [
            "block_per_turn:foo",
            "first_hit_double_damage:banana",
            "damage_below_health_percent:50:shadow:5",
            "turn_random_damage_all_enemies:burn:shadow",
            "bonusManaOnTurns:[1, banana]",
        ]:
            with self.subTest(token=token), self.assertRaises(ValueError):
                self.codegen.triggers_swift(token)

    def test_triggers_swift_bespoke_arity_errors_name_expected_shape(self) -> None:
        for token in [
            "damage_below_health_percent:50",
            "damage_below_health_percent:1:2:3:4",
            "once_below_health_percent_heal:10",
            "dodge_chance_below_health_percent:10",
            "turn_random_damage_all_enemies:burn:5",
            "cards_played_mana:1:2:3",
        ]:
            with self.subTest(token=token):
                with self.assertRaises(ValueError) as ctx:
                    self.codegen.triggers_swift(token)
                self.assertIn("expects", str(ctx.exception))

    def test_trigger_alias_targets_exist_in_schema(self) -> None:
        triggers = load_script("internal.content.content_codegen_triggers", "internal/content/content_codegen_triggers.py")
        names = {
            field["name"]
            for family in self.codegen._trigger_families()
            for field in family["fields"]
        }
        for token, field in list(triggers._TRIGGER_SIMPLE_MAP.items()) + list(
            triggers._FLAG_TRIGGERS.items()
        ):
            self.assertIn(field, names, f"alias {token!r} targets unknown field")
        for prefix, (_, arities) in triggers._BESPOKE_TRIGGER_SPECS.items():
            for fields in arities.values():
                for field, _ in fields:
                    self.assertIn(field, names, f"bespoke {prefix!r} sets unknown field")

    def test_modifiers_swift_rejects_duplicates_and_bad_amounts(self) -> None:
        with self.assertRaises(ValueError):
            self.codegen.modifiers_swift("maximum_health:4|maximum_health:8", "sample")
        with self.assertRaises(ValueError):
            self.codegen.modifiers_swift("damage_dealt:burn:1|damage_dealt:burn:2", "sample")
        for token in ["maximum_health:foo", "outgoing_damage_percent:foo", "damage_dealt:burn:foo"]:
            with self.subTest(token=token), self.assertRaises(ValueError):
                self.codegen.modifiers_swift(token, "sample")

    def test_homestead_combat_tokens_reject_duplicates_and_bad_bonuses(self) -> None:
        with self.assertRaises(ValueError):
            self.codegen.parse_homestead_combat_tokens("astral_chance:5|astral_chance:10")
        with self.assertRaises(ValueError):
            self.codegen.parse_homestead_combat_tokens("astral_chance:many")
        with self.assertRaises(ValueError):
            self.codegen.parse_homestead_combat_tokens(
                "companion.dodge_chance_bonus:0.02|companion.dodge_chance_bonus:0.04"
            )

    def test_manifest_table_rejects_ragged_rows(self) -> None:
        with tempfile.NamedTemporaryFile("w", suffix=".tsv", delete=False) as f:
            f.write("# id\tasset_name\n")
            f.write("only_one_column\n")
            temp_path = Path(f.name)
        try:
            with self.assertRaises(ValueError):
                self.codegen.read_manifest_table(temp_path)
        finally:
            temp_path.unlink(missing_ok=True)

    def _stage_row(self, **overrides: str) -> object:
        fields = {
            "chapter_id": "chapter-1",
            "chapter_number": "1",
            "chapter_title": "First",
            "theme": "forest",
            "stage_number": "1",
            "encounter": "battle",
            "enemy_id": "goblin",
            "encounter_art_id": "",
            "encounter_art_title": "",
        }
        fields.update(overrides)
        return self.codegen.StageRow(**fields)

    def test_stage_rows_validate_ids_numbering_and_art(self) -> None:
        good = [self._stage_row()]
        self.codegen.validate_stage_rows(
            good,
            enemy_ids={"goblin"},
            mystery_event_ids={"mana-berries"},
            recruit_event_ids={"recruit-knight"},
            art_ids={"destination-merchant-shop"},
        )
        with self.assertRaises(ValueError):
            self.codegen.validate_stage_rows(
                [self._stage_row(), self._stage_row()],
                enemy_ids={"goblin"},
            )
        with self.assertRaises(ValueError):
            self.codegen.validate_stage_rows(
                [self._stage_row(encounter="battle", enemy_id="")],
                enemy_ids={"goblin"},
            )
        with self.assertRaises(ValueError):
            self.codegen.validate_stage_rows(
                [
                    self._stage_row(stage_number="1"),
                    self._stage_row(stage_number="3"),
                ],
                enemy_ids={"goblin"},
            )
        with self.assertRaises(ValueError):
            self.codegen.validate_stage_rows(
                [self._stage_row(encounter="mystery", enemy_id="bogus-event")],
                enemy_ids={"goblin"},
                mystery_event_ids={"mana-berries"},
            )
        with self.assertRaises(ValueError):
            self.codegen.validate_stage_rows(
                [self._stage_row(encounter="recruit", enemy_id="bogus-event")],
                enemy_ids={"goblin"},
                recruit_event_ids={"recruit-knight"},
            )
        self.codegen.validate_stage_rows(
            [self._stage_row(encounter="recruit", enemy_id="random-companion")],
            enemy_ids={"goblin"},
            recruit_event_ids={"recruit-knight"},
        )
        with self.assertRaises(ValueError):
            self.codegen.validate_stage_rows(
                [
                    self._stage_row(
                        encounter="shop",
                        enemy_id="",
                        encounter_art_id="bogus-art",
                        encounter_art_title="Bogus",
                    )
                ],
                enemy_ids={"goblin"},
                art_ids={"destination-merchant-shop"},
            )

    def test_live_manifest_event_and_art_ids_resolve(self) -> None:
        self.assertIn("mana-berries", self.codegen.collect_mystery_event_ids())
        self.assertIn("recruit-knight", self.codegen.collect_recruit_event_ids())
        self.assertIn("destination-merchant-shop", self.codegen.collect_art_ids())

    def test_modifier_token_to_swift_multipart_keyword(self) -> None:
        self.assertEqual(
            self.codegen.modifier_token_to_swift("damage_dealt:burn:3"),
            ".damageDealt(.burn, 3)",
        )

    def test_modifier_token_to_swift_rejects_unknown_keyword(self) -> None:
        with self.assertRaises(ValueError):
            self.codegen.modifier_token_to_swift("damage_dealt:shadow:3")
        with self.assertRaises(ValueError):
            self.codegen.modifier_token_to_swift("damage_taken_percent:arcane:0.2")

    def test_modifier_token_to_swift_rejects_malformed_token(self) -> None:
        with self.assertRaises(ValueError):
            self.codegen.modifier_token_to_swift("damage_dealt:fire")

    def test_talent_validation_requires_known_combatant(self) -> None:
        row = self.codegen.TalentRow(
            id="unknown_hero_burn_t1_1",
            name="Flame",
            icon_id="lucide:flame",
            description="Burns target",
            modifiers="",
            triggers="",
        )
        with self.assertRaises(ValueError):
            self.codegen.validate_talent_rows([row], combatant_ids=["knight", "ranger"])

    def test_game_icons_require_a_provider_and_bundled_lucide_asset(self) -> None:
        for icon_id in ["flame.fill", "other:flame", "lucide:missing-trinket-icon", "lucide:../flame"]:
            with self.subTest(icon_id=icon_id), self.assertRaises(ValueError):
                self.codegen._validate_game_icon(icon_id, "sample")
        self.codegen._validate_game_icon("lucide:sword", "sample")
        self.codegen._validate_game_icon("sf:burst.fill", "sample")

    def test_parse_tsv_rows_pads_optional_columns_and_enforces_min_columns(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            tsv_path = Path(directory) / "test.tsv"
            tsv_path.write_text("id\tname\topt1\topt2\nitem1\tItem One\n", encoding="utf-8")
            from dataclasses import dataclass

            @dataclass
            class DummyRow:
                id: str
                name: str
                opt1: str
                opt2: str

            rows = self.codegen._parse_tsv_rows(tsv_path, ["id", "name", "opt1", "opt2"], DummyRow, min_columns=2)
            self.assertEqual(len(rows), 1)
            self.assertEqual(rows[0].id, "item1")
            self.assertEqual(rows[0].opt1, "")
            self.assertEqual(rows[0].opt2, "")

            with self.assertRaises(ValueError):
                self.codegen._parse_tsv_rows(tsv_path, ["id", "name", "opt1", "opt2"], DummyRow, min_columns=3)

    def test_inventory_digest_tracks_formatter_and_dependency_changes(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            files = ["Scripts/content_codegen.py", "Scripts/tool-versions.env",
                     "Packages/TrinketContent/Package.swift", "Packages/TrinketCore/Package.swift",
                     "Packages/TrinketContent/Sources/TrinketContent/Abilities/AbilityDescriptionFormatter.swift",
                     "Packages/TrinketCore/Sources/TrinketCore/Keyword.swift"]
            for name in files:
                path = root / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text("initial")
            with patch.object(self.codegen, "ROOT", root), patch.object(
                self.codegen, "TRINKET_CONTENT_PACKAGE", root / "Packages/TrinketContent"
            ):
                previous = self.codegen._ability_inventory_digest()
                self.assertEqual(previous, self.codegen._ability_inventory_digest())
                for name in files[-2:]:
                    path = root / name
                    path.write_text("changed")
                    current = self.codegen._ability_inventory_digest()
                    self.assertNotEqual(previous, current)
                    previous = current
                path.unlink()
                self.assertNotEqual(previous, self.codegen._ability_inventory_digest())

    def test_swift_escape_handles_quotes_backslashes_and_newlines(self) -> None:
        self.assertEqual(self.codegen.swift_escape("plain"), "plain")
        self.assertEqual(self.codegen.swift_escape('say "hi"'), 'say \\"hi\\"')
        self.assertEqual(self.codegen.swift_escape("deal {n} damage"), "deal {n} damage")
        self.assertEqual(self.codegen.swift_escape("a\\b"), "a\\\\b")
        self.assertEqual(
            self.codegen.swift_escape("Increase X by 1\\nProduces 1 Hide per day"),
            "Increase X by 1\\nProduces 1 Hide per day",
        )

    def test_write_if_changed_skips_rewrite_when_identical(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            path = Path(directory) / "Sample.generated.swift"
            self.codegen.write_if_changed(path, "content\n")
            self.assertEqual(path.read_text(encoding="utf-8"), "content\n")
            with patch.object(Path, "write_text") as writer:
                self.codegen.write_if_changed(path, "content\n")
                writer.assert_not_called()

    def test_ui_style_requires_explicit_catalog_artwork_display_size(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            fixture = Path(directory) / "ArtworkFixture.swift"
            fixture.write_text(
                "Image.preparedAsset(named: art.imageName)\n",
                encoding="utf-8",
            )
            rejected = subprocess.run(
                [sys.executable, str(ROOT / "Scripts" / "check-ui-style.py"), str(fixture)],
                cwd=ROOT,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertNotEqual(rejected.returncode, 0)
            self.assertIn("catalog artwork without explicit display size", rejected.stdout)

            fixture.write_text(
                "Image.preparedAsset(art, displaySize: .compact)\n",
                encoding="utf-8",
            )
            accepted = subprocess.run(
                [sys.executable, str(ROOT / "Scripts" / "check-ui-style.py"), str(fixture)],
                cwd=ROOT,
                capture_output=True,
                text=True,
                check=False,
            )
            self.assertEqual(accepted.returncode, 0, accepted.stdout + accepted.stderr)

    def test_ui_style_owns_product_color_policy(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            fixture = Path(directory) / "ColorFixture.swift"
            for source in (
                "let color = Color(red: 1, green: 0, blue: 0)\n",
                "let color = Color.red\n",
                "Text(\"Alert\").foregroundStyle(.red)\n",
                'let color = Color("Alert", bundle: .main)\n',
            ):
                fixture.write_text(source, encoding="utf-8")
                rejected = subprocess.run(
                    [sys.executable, str(ROOT / "Scripts" / "check-ui-style.py"), str(fixture)],
                    cwd=ROOT,
                    capture_output=True,
                    text=True,
                    check=False,
                )
                self.assertNotEqual(rejected.returncode, 0, source)

        swiftlint = (ROOT / ".swiftlint.yml").read_text(encoding="utf-8")
        platform = (ROOT / "Scripts" / "check-api-bans.sh").read_text(encoding="utf-8")
        self.assertNotIn("banned_system_color_literal", swiftlint)
        self.assertNotIn("SYSTEM_COLORS", platform)

    def test_ui_style_scans_directories_without_ripgrep(self) -> None:
        checker = load_script("check_ui_style", "check-ui-style.py")
        with tempfile.TemporaryDirectory() as directory:
            fixture = Path(directory) / "Nested" / "Style.swift"
            fixture.parent.mkdir()
            for source, expected in (("let color = Color.red\n", 1), ("let color = Color.primary\n", 0)):
                with self.subTest(source=source), patch.object(checker.subprocess, "run", side_effect=FileNotFoundError), patch("builtins.print"):
                    fixture.write_text(source)
                    self.assertEqual(checker.main(["check-ui-style.py", directory]), expected)

    def test_comment_ban_rejects_inline_and_block_comments(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            fixture = Path(directory) / "CommentFixture.swift"
            fixture.write_text(
                "let value = 1 // inline rationale\n"
                "/* block rationale */\n",
                encoding="utf-8",
            )

            result = subprocess.run(
                [str(ROOT / "Scripts" / "check-comment-ban.sh"), "--", str(fixture)],
                cwd=ROOT,
                capture_output=True,
                text=True,
                check=False,
            )

            self.assertNotEqual(result.returncode, 0)
            self.assertIn("Comment ban violations (2)", result.stderr)

    def test_comment_ban_keeps_toolchain_and_transitional_allowlist(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            fixture = Path(directory) / "AllowedCommentFixture.swift"
            fixture.write_text(
                "// swift-tools-version: 6.2\n"
                "struct Probe {} // swiftlint:disable:this type_body_length - fixture\n"
                "/// Concurrency-Safety: immutable fixture\n",
                encoding="utf-8",
            )

            result = subprocess.run(
                [str(ROOT / "Scripts" / "check-comment-ban.sh"), "--", str(fixture)],
                cwd=ROOT,
                capture_output=True,
                text=True,
                check=False,
            )

            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)

    def test_agent_invariants_cover_entropy_sleep_persistence_and_concurrency(self) -> None:
        text = (ROOT / "Scripts" / "check-agent-invariants.sh").read_text(encoding="utf-8")
        self.assertIn(r"\b(Date|UUID)\(\)", text)
        self.assertIn("Task.sleep", text)
        self.assertIn("PersistenceCheck", text)
        self.assertIn("@unchecked Sendable", text)
        self.assertIn("ArtworkWorkingSetCheck", text)
        self.assertIn("Trinket/App/TrinketApp.swift", text)
        self.assertIn("swiftlint:disable must include ' - <reason>'", text)
        self.assertIn(r"//[[:space:]]*swiftlint:disable", text)

    def test_accessibility_ids_reject_duplicate_constants_and_raw_uitest_literals(self) -> None:
        checker = load_script("check_accessibility_ids", "check-accessibility-ids.py")
        duplicates = checker.unique_constants()
        self.assertEqual(duplicates, [])
        raw = checker.raw_uitest_literals(checker.allowlist())
        self.assertEqual(raw, [], raw)

    def test_style_gate_invokes_agent_invariants_and_accessibility_ids(self) -> None:
        text = (ROOT / "Scripts" / "test.sh").read_text(encoding="utf-8")
        style_lib = (ROOT / "Scripts" / "lib" / "test-style.sh").read_text(encoding="utf-8")
        combined = text + style_lib
        self.assertIn("check-agent-invariants.sh", combined)
        self.assertIn("check-accessibility-ids.py", combined)

    def test_content_codegen_routes_generation_and_script_tests(self) -> None:
        result = subprocess.run(
            [
                str(ROOT / "Scripts" / "handoff.sh"),
                "--dry-run",
                "--paths",
                "Scripts/content_codegen.py",
            ],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        plan = "\n".join(result.stdout.splitlines())
        self.assertIn("./Scripts/generate.sh", plan)
        self.assertIn("./Scripts/test-scripts.sh", plan)

    def test_authored_content_swift_routes_generation_style_and_package(self) -> None:
        result = subprocess.run(
            [
                str(ROOT / "Scripts" / "handoff.sh"),
                "--dry-run",
                "--paths",
                "Packages/TrinketContent/Sources/TrinketContent/Abilities/AbilityCatalogBasic.swift",
            ],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=False,
        )
        self.assertEqual(result.returncode, 0, result.stderr)
        plan = [line.strip() for line in result.stdout.splitlines() if line.startswith("  ")]
        self.assertEqual(
            plan[:4],
            [
                "./Scripts/generate.sh",
                "./Scripts/assert-generated-output.sh --idempotent",
                "./Scripts/test.sh style Packages/TrinketContent/Sources/TrinketContent/Abilities/AbilityCatalogBasic.swift",
                "./Scripts/test-package.sh TrinketContent",
            ],
        )
        self.assertEqual(
            plan[4:],
            [
                "./Scripts/check-module-boundaries.sh",
                "./Scripts/release-notes.sh validate",
                "./Scripts/check-artwork-budget.sh",
            ],
        )

if __name__ == "__main__":
    unittest.main()
