"""Common content parsing, validation, and generation."""

from __future__ import annotations

from pathlib import Path
import csv
import functools
import re

from internal.cli import ROOT


MANIFEST_DIR = ROOT / "ContentManifest"


GENERATED_DIR = ROOT / "Packages" / "TrinketContent" / "Sources" / "TrinketContent" / "Generated"


VALID_HOMESTEAD_RESOURCES = frozenset(
    {"wood", "stone", "iron", "food", "herbs", "hide", "gems", "gold"}
)


SWIFT_IDENTIFIER = re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")


_KEBAB_BODY = r"[a-z0-9]+(?:-[a-z0-9]+)*"


KEBAB_IDENTIFIER = re.compile(rf"^{_KEBAB_BODY}$")


SNAKE_IDENTIFIER = re.compile(r"^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$")


@functools.cache
def _read_tsv_cached(path: Path) -> tuple[tuple[str, ...], ...]:
    rows: list[tuple[str, ...]] = []
    with path.open(newline="", encoding="utf-8") as handle:
        for fields in csv.reader(handle, delimiter="\t"):
            if not fields or (len(fields) == 1 and not fields[0]):
                continue
            if fields[0].startswith("#"):
                continue
            rows.append(tuple(fields))
    return tuple(rows)


def read_tsv(path: Path) -> list[list[str]]:
    return [list(row) for row in _read_tsv_cached(path)]


def _parse_tsv_rows(path: Path, expected: list[str], row_type, min_columns: int | None = None):
    lines = read_tsv(path)
    header = lines[0]
    if header != expected:
        raise ValueError(f"{path} header mismatch: {header}")
    min_cols = min_columns if min_columns is not None else len(expected)
    rows: list = []
    for idx, raw in enumerate(lines[1:], start=2):
        if len(raw) < min_cols:
            raise ValueError(f"{path}:{idx} missing required columns: expected at least {min_cols}, got {len(raw)}")
        if len(raw) > len(expected):
            raise ValueError(f"{path}:{idx} has {len(raw)} columns, expected {len(expected)}")
        padded = raw + [""] * (len(expected) - len(raw))
        rows.append(row_type(*padded[: len(expected)]))
    return rows


# Trailing DSL columns may be omitted (no trailing tabs required); missing
# trailing values parse as "". Affixes carry two trailing trigger columns,
# talents carry trailing modifiers/triggers. All other manifests require
# full-width rows.
AFFIX_REQUIRED_COLUMNS = 9


TALENT_REQUIRED_COLUMNS = 4


def read_manifest_table(path: Path) -> tuple[list[str], list[list[str]]]:
    """Shared #-header TSV reader for media manifests.

    Skips blank lines and #-comments; the first content row is the header with
    its leading # stripped. Ragged rows are rejected so truncated inputs fail
    fast instead of silently dropping columns.
    """
    with path.open(newline="", encoding="utf-8") as handle:
        raw_rows = list(csv.reader(handle, delimiter="\t"))
    header: list[str] = []
    rows: list[list[str]] = []
    for line_number, row in enumerate(raw_rows, start=1):
        if not row or (len(row) == 1 and not row[0].strip()):
            continue
        if not header:
            if not row[0].lstrip().startswith("#"):
                raise ValueError(f"{path}:{line_number} manifest header must start with #")
            header = [row[0].lstrip("#").strip()] + [cell.strip() for cell in row[1:]]
            continue
        if row[0].lstrip().startswith("#"):
            continue
        if len(row) != len(header):
            raise ValueError(
                f"{path}:{line_number} has {len(row)} columns, expected {len(header)}"
            )
        rows.append([cell.strip() for cell in row])
    if not header:
        raise ValueError(f"{path} has no header row")
    return header, rows


def swift_escape(value: str) -> str:
    """Escape a manifest string for a Swift literal.

    Manifests spell newlines as a literal backslash-n (see homestead bonus
    descriptions); those become real newlines first so the final pass escapes
    every backslash, quote, and newline exactly once.
    """
    value = value.replace("\\n", "\n")
    return value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def parse_keywords(raw: str) -> str:
    if not raw:
        return "[]"
    parts = [part.strip() for part in raw.split(",") if part.strip()]
    return "[" + ", ".join(f".{part}" for part in parts) + "]"


def write_generated_file(path: Path, body: str) -> None:
    content = (
        "// Generated by Scripts/content_codegen.py — do not edit.\n"
        "import Foundation\n"
        "import TrinketCore\n\n"
        f"{body}\n"
    )
    write_if_changed(path, content)


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    # Skip rewrite when content is unchanged so mtimes do not invalidate dependents.
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return
    path.write_text(content, encoding="utf-8")


def list_catalog_property(
    prop: str, item_type: str, entries: list[str], chunk_size: int | None = None
) -> str:
    if chunk_size is None:
        appends = "\n".join(f"        list.append({entry.strip()})" for entry in entries)
        return (
            f"    static let {prop}: [{item_type}] = {{\n"
            f"        var list = [{item_type}]()\n"
            f"        list.reserveCapacity({len(entries)})\n"
            + appends
            + "\n        return list\n"
            "    }()\n"
        )
    chunks = [entries[index:index + chunk_size] for index in range(0, len(entries), chunk_size)]
    chunk_appends = "\n".join(
        f"        list.append(contentsOf: chunk{index}())" for index in range(len(chunks))
    )
    chunk_functions = "\n\n".join(
        "    private static func chunk"
        f"{index}() -> [{item_type}] {{\n"
        "        [\n"
        + ",\n".join(entry for entry in chunk)
        + "\n        ]\n"
        "    }"
        for index, chunk in enumerate(chunks)
    )
    return (
        f"    static let {prop}: [{item_type}] = {{\n"
        f"        var list = [{item_type}]()\n"
        f"        list.reserveCapacity({len(entries)})\n"
        + chunk_appends
        + "\n        return list\n"
        "    }()\n"
        "\n"
        + chunk_functions
        + "\n"
    )


def _validate_snake_id(label: str, value: str, row_id: str) -> None:
    if not SNAKE_IDENTIFIER.match(value):
        raise ValueError(
            f"{label} '{value}' for {row_id} must use lowercase letters, numbers, and underscores"
        )


def _validate_positive_int(label: str, value: str, row_id: str, minimum: int = 0) -> None:
    if not value.isdigit():
        raise ValueError(f"{label} for {row_id} must be an integer")
    if int(value) < minimum:
        if minimum == 1:
            raise ValueError(f"{label} for {row_id} must be positive")
        raise ValueError(f"{label} for {row_id} must be non-negative")


def _require_non_empty(label: str, value: str, row_id: str) -> None:
    if not value.strip():
        raise ValueError(f"{label} is required for {row_id}")


def _validate_swift_symbol(label: str, value: str, row_id: str) -> None:
    if not SWIFT_IDENTIFIER.match(value):
        raise ValueError(f"{label} '{value}' for {row_id} must be a valid Swift identifier")


def parse_material_tokens(raw: str) -> list[tuple[str, int]]:
    tokens: list[tuple[str, int]] = []
    for token in raw.split("|"):
        token = token.strip()
        if not token:
            continue
        if ":" not in token:
            raise ValueError(f"Cost entry {token!r} must be resource:amount")
        resource, quantity = token.split(":", 1)
        resource = resource.strip()
        if resource not in VALID_HOMESTEAD_RESOURCES:
            raise ValueError(f"Unknown homestead resource '{resource}'")
        try:
            amount = int(quantity.strip())
        except ValueError as error:
            raise ValueError(f"Cost quantity {quantity.strip()!r} must be an integer") from error
        tokens.append((resource, amount))
    return tokens


def parse_material_rewards(raw: str) -> str:
    if not raw.strip():
        return "[]"
    amounts = [
        f"ResourceAmount(.{resource}, {quantity})"
        for resource, quantity in parse_material_tokens(raw)
    ]
    return "[" + ", ".join(amounts) + "]"


def _ensure_unique(seen: set[str], value: str, label: str) -> None:
    """Single home for duplicate-ID checks; replaces repeated seen-set blocks."""
    if value in seen:
        raise ValueError(f"Duplicate {label}: {value}")
    seen.add(value)


def _validate_game_icon(icon_id: str, row_id: str) -> None:
    if not re.fullmatch(r"sf:[a-z0-9]+(?:\.[a-z0-9]+)*", icon_id):
        raise ValueError(f"Invalid icon_id '{icon_id}' for {row_id}; use sf:name")
