#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

manifest="SoundManifest/sfx.tsv"
generated_dir="Packages/TrinketContent/Sources/TrinketContent/Generated"
generated_swift="$generated_dir/SFXCatalog.generated.swift"

if [[ ! -f "$manifest" ]]; then
  echo "Missing manifest: $manifest" >&2
  exit 1
fi

mkdir -p "$generated_dir"

entries_temp=$(mktemp)
processed_count=0

escape_swift_string() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

while IFS=$'\t' read -r id resource_name file_extension volume_gain || [[ -n "${id:-}" ]]; do
  [[ -z "${id:-}" || "$id" == \#* || "$id" == "id" ]] && continue

  if [[ -z "$resource_name" || -z "$file_extension" || -z "$volume_gain" ]]; then
    echo "Manifest row is missing required fields for id '$id'." >&2
    exit 1
  fi

  escaped_id="$(escape_swift_string "$id")"
  escaped_resource="$(escape_swift_string "$resource_name")"
  escaped_extension="$(escape_swift_string "$file_extension")"

  cat >> "$entries_temp" <<SWIFT
        SFXClip(
            id: "$escaped_id",
            resourceName: "$escaped_resource",
            fileExtension: "$escaped_extension",
            volumeGain: $volume_gain
        ),
SWIFT
  processed_count=$((processed_count + 1))
done < "$manifest"

cat > "$generated_swift" <<'SWIFT'
// Generated by Scripts/prepare-sfx-assets.sh. Do not edit directly.

import Foundation

public struct SFXClip: Identifiable, Hashable, Sendable {
    public let id: String
    public let resourceName: String
    public let fileExtension: String
    public let volumeGain: Double
}

public enum SFXCatalog {
    public static let clips: [SFXClip] = [
SWIFT

if [[ -s "$entries_temp" ]]; then
  cat "$entries_temp" >> "$generated_swift"
else
  echo "        // Add rows to SoundManifest/sfx.tsv when sound sources are ready." >> "$generated_swift"
fi

cat >> "$generated_swift" <<'SWIFT'
    ]

    public static let clipsByID: [String: SFXClip] = {
        Dictionary(uniqueKeysWithValues: clips.map { ($0.id, $0) })
    }()
}
SWIFT

rm -f "$entries_temp"

echo "Prepared $processed_count SFX catalog entr(ies)."
