#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

source_dir="Raw Assets/App Icon/Trinket-Icon-v1 Exports"
target_dir="Trinket/Assets.xcassets/AppIcon.appiconset"
generated_dir="Packages/TrinketContent/Sources/TrinketContent/Generated"
state_file="$generated_dir/AppIconSourceHashes.generated.tsv"

if [[ ! -d "$source_dir" ]]; then
  echo "Missing source directory: $source_dir" >&2
  exit 1
fi
mkdir -p "$target_dir" "$generated_dir"

# App Store icons must stay PNG. These sources are photographic RGBA (~4MB each);
# lossless recompression barely helps. Copy the source unchanged so alpha and
# every source pixel are preserved.
install_compressed_app_icon() {
  local src="$1"
  local dst="$2"
  local tmp_output size_label
  tmp_output="$(dirname "$dst")/.$(basename "$dst").tmp.$$"
  rm -f "$tmp_output"
  cp "$src" "$tmp_output"
  [[ -s "$tmp_output" ]] || return 1
  mv -f "$tmp_output" "$dst"
  size_label="$(du -h "$dst" | awk '{print $1}')"
  echo "  Installed $dst ($size_label)"
}

echo "=== Preparing app icon ==="

sources=(
  "Trinket-Icon-v1-iOS-Default-1024x1024@1x.png"
  "Trinket-Icon-v1-iOS-Dark-1024x1024@1x.png"
)
destinations=("AppIcon-Default.png" "AppIcon-Dark.png")

for src in "${sources[@]}"; do
  if [[ ! -f "$source_dir/$src" ]]; then
    echo "Missing required app icon source: $src" >&2
    exit 1
  fi
done

state_temp="$state_file.tmp.$$"
if [[ -f "$state_file" ]]; then
  cp "$state_file" "$state_temp"
else
  printf '%s\n' '# Generated by Scripts/prepare-app-icon.sh. Do not edit directly.' > "$state_temp"
  printf '%s\t%s\n' '# asset_name' 'source_sha256' >> "$state_temp"
fi
cleanup() {
  rm -f "$state_temp" "$state_temp.next" "$state_temp.sorted" "$target_dir"/.*.tmp.$$ 2>/dev/null || true
}
trap cleanup EXIT

for index in "${!sources[@]}"; do
  src="${sources[$index]}"
  dst="${destinations[$index]}"
  source_hash="$(shasum -a 256 "$source_dir/$src" | awk '{print $1}')"
  recorded_hash="$(awk -F$'\t' -v name="$dst" '$1 == name { print $2; exit }' "$state_file" 2>/dev/null || true)"
  output_hash=""
  if [[ -f "$target_dir/$dst" ]]; then
    output_hash="$(shasum -a 256 "$target_dir/$dst" | awk '{print $1}')"
  fi
  if [[ "${FORCE_ASSET_REENCODE:-0}" != "1" ]] \
    && [[ "$recorded_hash" == "$source_hash" && "$output_hash" == "$source_hash" ]]; then
    :
  else
    install_compressed_app_icon "$source_dir/$src" "$target_dir/$dst"
  fi
  awk -F$'\t' -v name="$dst" '$1 != name { print }' "$state_temp" > "$state_temp.next"
  printf '%s\t%s\n' "$dst" "$source_hash" >> "$state_temp.next"
  mv -f "$state_temp.next" "$state_temp"
done
sort -t$'\t' -k1,1 "$state_temp" > "$state_temp.sorted"
mv -f "$state_temp.sorted" "$state_temp"
mv -f "$state_temp" "$state_file"

echo "=== App icon ready ==="
