#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

manifest="SoundManifest/sfx.tsv"
resources_dir="Trinket/Media/SFX"
generated_dir="Packages/TrinketContent/Sources/TrinketContent/Generated"
generated_swift="$generated_dir/SFXCatalog.generated.swift"
state_file="$generated_dir/SFXSourceHashes.generated.tsv"
bitrate="${SFX_AAC_BITRATE:-64000}"

if [[ ! -f "$manifest" ]]; then
  echo "Missing manifest: $manifest" >&2
  exit 1
fi

if ! command -v afconvert >/dev/null 2>&1; then
  echo "Missing required tool: afconvert" >&2
  exit 1
fi

mkdir -p "$resources_dir" "$generated_dir"

clips_temp=$(mktemp)
seen_ids_temp=$(mktemp)
seen_assets_temp=$(mktemp)
active_clips_temp=$(mktemp)
processed_count=0
state_temp="$state_file.tmp.$$"
state_was_present=false
if [[ -f "$state_file" ]]; then
  cp "$state_file" "$state_temp"
  state_was_present=true
else
  printf '%s\n' '# Generated by Scripts/prepare-sfx-assets.sh. Do not edit directly.' > "$state_temp"
  printf '%s\t%s\n' '# asset_name' 'source_sha256' >> "$state_temp"
fi
cleanup() {
  rm -f "$clips_temp" "$seen_ids_temp" "$seen_assets_temp" "$active_clips_temp" "$state_temp" "$state_temp.next" "$state_temp.sorted" \
    "${generated_temp:-}" "$resources_dir"/.*.tmp.$$.* 2>/dev/null || true
}
trap cleanup EXIT

escape_swift_string() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

validate_identifier() {
  local label="$1" value="$2"
  if [[ ! "$value" =~ ^[A-Za-z0-9_][A-Za-z0-9_-]*$ ]]; then
    echo "$label '$value' should use letters, numbers, hyphens, or underscores, and start with a letter, number, or underscore." >&2
    exit 1
  fi
}

while IFS=$'\t' read -r id asset_name source_path volume_gain || [[ -n "${id:-}" ]]; do
  [[ -z "${id:-}" || "$id" == \#* ]] && continue

  if [[ -z "$asset_name" || -z "$source_path" || -z "$volume_gain" ]]; then
    echo "Manifest row is missing required fields for id '$id'." >&2
    exit 1
  fi

  validate_identifier "SFX id" "$id"
  validate_identifier "Asset name" "$asset_name"

  if grep -qx "$id" "$seen_ids_temp"; then
    echo "Duplicate SFX id '$id'." >&2
    exit 1
  fi
  printf '%s\n' "$id" >> "$seen_ids_temp"

  if grep -qx "$asset_name" "$seen_assets_temp"; then
    echo "Duplicate SFX asset name '$asset_name'." >&2
    exit 1
  fi
  printf '%s\n' "$asset_name" >> "$seen_assets_temp"

  if [[ ! -f "$source_path" ]]; then
    echo "Missing source file for '$id': $source_path" >&2
    exit 1
  fi

  if [[ ! "$volume_gain" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
    echo "Volume gain for '$id' must be numeric." >&2
    exit 1
  fi

  printf '%s\n' "$asset_name.m4a" >> "$active_clips_temp"

  output_file="$resources_dir/$asset_name.m4a"

  source_hash="$(shasum -a 256 "$source_path" | awk '{print $1}')"
  recorded_hash="$(awk -F$'\t' -v name="$asset_name" '$1 == name { print $2; exit }' "$state_file" 2>/dev/null || true)"
  needs_convert=false
  if [[ "${FORCE_ASSET_REENCODE:-0}" == "1" ]] \
    || [[ "$state_was_present" == false && ! -f "$output_file" ]] \
    || [[ "$state_was_present" == true && "$recorded_hash" != "$source_hash" ]] \
    || [[ ! -f "$output_file" && "$state_was_present" == true ]]; then
    needs_convert=true
  fi

  if $needs_convert; then
    tmp_output="$resources_dir/.${asset_name}.tmp.$$.m4a"
    rm -f "$tmp_output"
    if ! afconvert "$source_path" "$tmp_output" -f m4af -d aac -b "$bitrate" --soundcheck-generate >/dev/null \
      || [[ ! -s "$tmp_output" ]]; then
      rm -f "$tmp_output"
      echo "Failed to produce a valid SFX asset for '$id'." >&2
      exit 1
    fi
    mv -f "$tmp_output" "$output_file"
  fi
  awk -F$'\t' -v name="$asset_name" '$1 != name { print }' "$state_temp" > "$state_temp.next"
  printf '%s\t%s\n' "$asset_name" "$source_hash" >> "$state_temp.next"
  mv -f "$state_temp.next" "$state_temp"

  escaped_id="$(escape_swift_string "$id")"
  escaped_asset="$(escape_swift_string "$asset_name")"

  cat >> "$clips_temp" <<SWIFT
        SFXClip(
            id: "$escaped_id",
            resourceName: "$escaped_asset",
            fileExtension: "m4a",
            volumeGain: $volume_gain
        ),
SWIFT

  processed_count=$((processed_count + 1))
done < "$manifest"

generated_temp=$(mktemp)
cat > "$generated_temp" <<SWIFT
// Generated by Scripts/prepare-sfx-assets.sh. Do not edit directly.

import Foundation

public struct SFXClip: Identifiable, Hashable, Sendable {
    public let id: String
    public let resourceName: String
    public let fileExtension: String
    public let volumeGain: Double
}

public enum SFXCatalog {
    public static let clips: [SFXClip] = [
$(cat "$clips_temp")
    ]

    public static let clipsByID: [String: SFXClip] = {
        Dictionary(uniqueKeysWithValues: clips.map { (\$0.id, \$0) })
    }()
}
SWIFT

if [[ -f "$generated_swift" ]] && cmp -s "$generated_temp" "$generated_swift"; then
  rm -f "$generated_temp"
else
  mv "$generated_temp" "$generated_swift"
fi

# Prune orphaned SFX assets
shopt -s nullglob
for file in "$resources_dir"/*.m4a; do
  [[ -f "$file" ]] || continue
  filename=$(basename "$file")
  if ! grep -qx "$filename" "$active_clips_temp"; then
    echo "Pruning orphaned SFX clip: $filename"
    rm -f "$file"
  fi
done
shopt -u nullglob

{
  head -n 2 "$state_temp"
  tail -n +3 "$state_temp" | LC_ALL=C sort -t$'\t' -k1,1
} > "$state_temp.sorted"
if [[ -f "$state_file" ]] && cmp -s "$state_temp.sorted" "$state_file"; then
  rm -f "$state_temp.sorted" "$state_temp"
else
  mv -f "$state_temp.sorted" "$state_file"
  rm -f "$state_temp"
fi
rm -f "$clips_temp" "$seen_ids_temp" "$seen_assets_temp" "$active_clips_temp"

echo "Prepared $processed_count SFX assets in $resources_dir and regenerated $generated_swift."
