#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
# shellcheck source=lib/media-assets.sh
source "Scripts/lib/media-assets.sh"

# Icon Composer package is the authored source for iOS 26 Liquid Glass icons.
# Install as AppIcon.icon so ASSETCATALOG_COMPILER_APPICON_NAME (default AppIcon) matches.
source_icon="Raw Assets/App Icon/Trinket App Icon.icon"
target_icon="Trinket/AppIcon.icon"
legacy_appiconset="Trinket/Assets.xcassets/AppIcon.appiconset"
generated_dir="Packages/TrinketContent/Sources/TrinketContent/Generated"
state_file="$generated_dir/AppIconSourceHashes.generated.tsv"
asset_name="AppIcon.icon"

install_icon_package() {
  local src="$1"
  local dst="$2"
  local tmp_output
  tmp_output="$(dirname "$dst")/.$(basename "$dst").tmp.$$"
  rm -rf "$tmp_output"
  mkdir -p "$(dirname "$dst")"
  cp -R "$src" "$tmp_output"
  # Drop Finder metadata that can appear when copying packages from Finder.
  find "$tmp_output" -name '.DS_Store' -delete 2>/dev/null || true
  rm -rf "$dst"
  mv -f "$tmp_output" "$dst"
  echo "  Installed $dst"
}

echo "=== Preparing app icon ==="

if [[ ! -d "$source_icon" ]]; then
  echo "Missing Icon Composer source: $source_icon" >&2
  echo "Author the icon in Icon Composer and save it under Raw Assets/App Icon/." >&2
  exit 1
fi
if [[ ! -f "$source_icon/icon.json" ]]; then
  echo "Icon Composer package is missing icon.json: $source_icon" >&2
  exit 1
fi

mkdir -p "$generated_dir"

source_hash="$(trinket_hash_dir_tree "$source_icon")"
trinket_asset_begin_state_lookup "$state_file"
trinket_asset_read_recorded_state recorded_hash recorded_profile "$asset_name"
output_hash=""
if [[ -d "$target_icon" ]]; then
  output_hash="$(trinket_hash_dir_tree "$target_icon")"
fi

if [[ "${FORCE_ASSET_REENCODE:-0}" != "1" ]] \
  && [[ "$recorded_hash" == "$source_hash" && "$output_hash" == "$source_hash" ]]; then
  :
else
  install_icon_package "$source_icon" "$target_icon"
fi

# Legacy PNG appiconset conflicts with AppIcon.icon; remove after Icon Composer install.
if [[ -d "$legacy_appiconset" ]]; then
  rm -rf "$legacy_appiconset"
  echo "  Removed legacy $legacy_appiconset"
fi

state_temp="$state_file.tmp.$$"
cleanup() {
  rm -f "$state_temp" "$state_temp.sorted" 2>/dev/null || true
  rm -rf "$(dirname "$target_icon")/.$(basename "$target_icon").tmp.$$" 2>/dev/null || true
}
trap cleanup EXIT

printf '%s\n' '# Generated by Scripts/prepare-app-icon.sh. Do not edit directly.' > "$state_temp"
printf '%s\t%s\t%s\n' '# asset_name' 'source_sha256' 'encode_profile' >> "$state_temp"
printf '%s\t%s\t%s\n' "$asset_name" "$source_hash" 'copy' >> "$state_temp"
trinket_asset_sort_state "$state_temp" "$state_file"

echo "=== App icon ready ==="
