#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
# shellcheck source=lib/media-assets.sh
source "Scripts/lib/media-assets.sh"

manifest="MusicManifest/music.tsv"
resources_dir="Trinket/Media/Music"
generated_dir="Packages/TrinketContent/Sources/TrinketContent/Generated"
generated_swift="$generated_dir/MusicCatalog.generated.swift"
state_file="$generated_dir/MusicSourceHashes.generated.tsv"
bitrate="${MUSIC_AAC_BITRATE:-96000}"

if [[ ! -f "$manifest" ]]; then
  echo "Missing manifest: $manifest" >&2
  exit 1
fi

if ! command -v afconvert >/dev/null 2>&1; then
  echo "Missing required tool: afconvert" >&2
  exit 1
fi

mkdir -p "$resources_dir" "$generated_dir"

tracks_temp=$(mktemp)
menu_temp=$(mktemp)
battle_temp=$(mktemp)
boss_temp=$(mktemp)
seen_ids_temp=$(mktemp)
seen_assets_temp=$(mktemp)
seen_boss_ids_temp=$(mktemp)
active_tracks_temp=$(mktemp)
processed_count=0
state_temp="$state_file.tmp.$$"
state_was_present=false
if [[ -f "$state_file" ]]; then
  cp "$state_file" "$state_temp"
  state_was_present=true
else
  printf '%s\n' '# Generated by Scripts/prepare-music-assets.sh. Do not edit directly.' > "$state_temp"
  printf '%s\t%s\n' '# asset_name' 'source_sha256' >> "$state_temp"
fi
cleanup() {
  rm -f "$tracks_temp" "$menu_temp" "$battle_temp" "$boss_temp" "$seen_ids_temp" "$seen_assets_temp" \
    "$seen_boss_ids_temp" "$active_tracks_temp" "$state_temp" "$state_temp.next" "$state_temp.sorted" "${generated_temp:-}" \
    "$resources_dir"/.*.tmp.$$.* 2>/dev/null || true
}
trap cleanup EXIT

while IFS=$'\t' read -r kind id asset_name source_path boss_enemy_id looping volume_gain || [[ -n "${kind:-}" ]]; do
  [[ -z "${kind:-}" || "$kind" == \#* ]] && continue
  [[ "$boss_enemy_id" == "none" ]] && boss_enemy_id=""

  if [[ "$kind" != "menu" && "$kind" != "battle" && "$kind" != "boss" ]]; then
    echo "Unsupported music kind '$kind' for id '$id'." >&2
    exit 1
  fi

  if [[ -z "$id" || -z "$asset_name" || -z "$source_path" || -z "$looping" || -z "$volume_gain" ]]; then
    echo "Manifest row is missing required fields for id '$id'." >&2
    exit 1
  fi

  trinket_asset_validate_identifier "Track id" "$id"
  trinket_asset_validate_identifier "Asset name" "$asset_name"

  if grep -qx "$id" "$seen_ids_temp"; then
    echo "Duplicate music track id '$id'." >&2
    exit 1
  fi
  printf '%s\n' "$id" >> "$seen_ids_temp"

  if grep -qx "$asset_name" "$seen_assets_temp"; then
    echo "Duplicate music asset name '$asset_name'." >&2
    exit 1
  fi
  printf '%s\n' "$asset_name" >> "$seen_assets_temp"

  if [[ ! -f "$source_path" ]]; then
    echo "Missing source file for '$id': $source_path" >&2
    exit 1
  fi

  case "$looping" in
    true|false) ;;
    *)
      echo "Looping value for '$id' must be true or false." >&2
      exit 1
      ;;
  esac

  if [[ ! "$volume_gain" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
    echo "Volume gain for '$id' must be numeric." >&2
    exit 1
  fi

  if [[ "$kind" == "boss" ]]; then
    if [[ -z "$boss_enemy_id" ]]; then
      echo "Boss music '$id' must include boss_enemy_id." >&2
      exit 1
    fi
    if ! awk -v id="$boss_enemy_id" '$0 ~ ("id: \"" id "\"") && $0 ~ /isBoss: true/ { found = 1 } END { exit !found }' Packages/TrinketContent/Sources/TrinketContent/Generated/GameContentEnemies.generated.swift; then
      echo "Boss music '$id' references missing or non-boss enemy '$boss_enemy_id'." >&2
      exit 1
    fi
    if grep -Fqx "$boss_enemy_id" "$seen_boss_ids_temp"; then
      echo "Duplicate boss music enemy id '$boss_enemy_id'." >&2
      exit 1
    fi
    printf '%s\n' "$boss_enemy_id" >> "$seen_boss_ids_temp"
  elif [[ -n "$boss_enemy_id" ]]; then
    echo "Only boss music may include boss_enemy_id; '$id' has '$boss_enemy_id'." >&2
    exit 1
  fi

  # Track active assets for pruning
  printf '%s\n' "$asset_name.m4a" >> "$active_tracks_temp"

  output_file="$resources_dir/$asset_name.m4a"

  source_hash="$(shasum -a 256 "$source_path" | awk '{print $1}')"
  recorded_hash="$(awk -F$'\t' -v name="$asset_name" '$1 == name { print $2; exit }' "$state_file" 2>/dev/null || true)"
  needs_convert=false
  if trinket_asset_needs_reencode "$state_was_present" "$recorded_hash" "$source_hash" "$output_file"; then
    needs_convert=true
  fi

  if $needs_convert; then
    tmp_output="$resources_dir/.${asset_name}.tmp.$$.m4a"
    rm -f "$tmp_output"
    trinket_asset_convert_aac "$source_path" "$tmp_output" "$bitrate" "music '$id'"
    mv -f "$tmp_output" "$output_file"
  fi
  awk -F$'\t' -v name="$asset_name" '$1 != name { print }' "$state_temp" > "$state_temp.next"
  printf '%s\t%s\n' "$asset_name" "$source_hash" >> "$state_temp.next"
  mv -f "$state_temp.next" "$state_temp"

  escaped_id="$(trinket_asset_escape_swift_string "$id")"
  escaped_asset="$(trinket_asset_escape_swift_string "$asset_name")"
  escaped_boss="$(trinket_asset_escape_swift_string "$boss_enemy_id")"

  cat >> "$tracks_temp" <<SWIFT
        MusicTrack(
            id: "$escaped_id",
            kind: .$kind,
            resourceName: "$escaped_asset",
            fileExtension: "m4a",
            bossEnemyID: "$escaped_boss",
            isLooping: $looping,
            volumeGain: $volume_gain
        ),
SWIFT

  case "$kind" in
    menu)
      cat >> "$menu_temp" <<SWIFT
        "$escaped_id",
SWIFT
      ;;
    battle)
      cat >> "$battle_temp" <<SWIFT
        "$escaped_id",
SWIFT
      ;;
    boss)
      cat >> "$boss_temp" <<SWIFT
        "$escaped_boss": "$escaped_id",
SWIFT
      ;;
  esac

  processed_count=$((processed_count + 1))
done < "$manifest"

generated_temp=$(mktemp)
cat > "$generated_temp" <<SWIFT
// Generated by Scripts/prepare-music-assets.sh. Do not edit directly.

import Foundation

public enum MusicCatalog {
    public static let allTracks: [MusicTrack] = [
$(cat "$tracks_temp")
    ]

    public static let menuTrackIDs: [String] = [
$(cat "$menu_temp")
    ]

    public static let battleTrackIDs: [String] = [
$(cat "$battle_temp")
    ]

    public static let bossTrackIDByEnemyID: [String: String] = [
$(cat "$boss_temp")
    ]
}
SWIFT

if [[ -f "$generated_swift" ]] && cmp -s "$generated_temp" "$generated_swift"; then
  rm -f "$generated_temp"
else
  mv "$generated_temp" "$generated_swift"
fi

trinket_asset_prune_orphans "$resources_dir" "$active_tracks_temp" "music track"
trinket_asset_sort_state "$state_temp" "$state_file"
rm -f "$tracks_temp" "$menu_temp" "$battle_temp" "$boss_temp" "$seen_ids_temp" "$seen_assets_temp" "$seen_boss_ids_temp" "$active_tracks_temp"

echo "Prepared $processed_count music assets in $resources_dir and regenerated $generated_swift."
