#!/bin/zsh
set -euo pipefail

cd "$(dirname "$0")/.."

manifest="Art/curated-assets.tsv"
asset_catalog="Trinket/Assets.xcassets"
generated_dir="Trinket/Generated"
generated_swift="$generated_dir/ArtCatalog.generated.swift"
max_dimension="${ART_MAX_DIMENSION:-1600}"

if [[ ! -f "$manifest" ]]; then
  echo "Missing manifest: $manifest" >&2
  exit 1
fi

mkdir -p "$asset_catalog" "$generated_dir"

rm -rf "$asset_catalog"/hero_*.imageset
rm -rf "$asset_catalog"/pet_*.imageset
rm -rf "$asset_catalog"/enemy_*.imageset

cat > "$asset_catalog/Contents.json" <<'JSON'
{
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
JSON

cat > "$generated_swift" <<'SWIFT'
// Generated by Scripts/prepare-art-assets.sh. Do not edit directly.

import SwiftUI

struct CombatantArtReference: Hashable {
    let imageName: String
    let focalPoint: UnitPoint
    let accessibilityLabel: String
}

enum ArtCatalog {
    static let combatantArtByID: [String: CombatantArtReference] = [
SWIFT

processed_count=0

escape_swift_string() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

while IFS=$'\t' read -r kind id asset_name source_path focal_x focal_y accessibility_label || [[ -n "${kind:-}" ]]; do
  [[ -z "${kind:-}" || "$kind" == \#* ]] && continue

  if [[ "$kind" != "combatant" ]]; then
    echo "Unsupported art kind '$kind' for id '$id'." >&2
    exit 1
  fi

  if [[ -z "$id" || -z "$asset_name" || -z "$source_path" || -z "$focal_x" || -z "$focal_y" || -z "$accessibility_label" ]]; then
    echo "Manifest row is missing required fields for id '$id'." >&2
    exit 1
  fi

  if [[ ! "$asset_name" =~ '^[A-Za-z0-9_]+$' ]]; then
    echo "Asset name '$asset_name' should use only letters, numbers, and underscores." >&2
    exit 1
  fi

  if [[ ! "$focal_x" =~ '^[0-9]+([.][0-9]+)?$' || ! "$focal_y" =~ '^[0-9]+([.][0-9]+)?$' ]]; then
    echo "Focal values for '$id' must be numeric." >&2
    exit 1
  fi

  source_file="$source_path"
  if [[ ! -f "$source_file" ]]; then
    echo "Missing source file for '$id': $source_path" >&2
    exit 1
  fi

  imageset="$asset_catalog/$asset_name.imageset"
  output_file="$imageset/$asset_name.jpg"

  rm -rf "$imageset"
  mkdir -p "$imageset"

  sips -s format jpeg -Z "$max_dimension" "$source_file" --out "$output_file" >/dev/null

  cat > "$imageset/Contents.json" <<JSON
{
  "images" : [
    {
      "filename" : "$asset_name.jpg",
      "idiom" : "universal"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
JSON

  escaped_id="$(escape_swift_string "$id")"
  escaped_asset="$(escape_swift_string "$asset_name")"
  escaped_label="$(escape_swift_string "$accessibility_label")"

  cat >> "$generated_swift" <<SWIFT
        "$escaped_id": CombatantArtReference(
            imageName: "$escaped_asset",
            focalPoint: UnitPoint(x: $focal_x, y: $focal_y),
            accessibilityLabel: "$escaped_label"
        ),
SWIFT

  processed_count=$((processed_count + 1))
done < "$manifest"

cat >> "$generated_swift" <<'SWIFT'
    ]
}

extension Combatant {
    var artReference: CombatantArtReference? {
        ArtCatalog.combatantArtByID[id]
    }
}
SWIFT

echo "Prepared $processed_count curated art asset(s)."
