#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
# shellcheck source=lib/media-assets.sh
source "Scripts/lib/media-assets.sh"

manifest="CinematicManifest/cinematics.tsv"
resources_dir="Trinket/Media/Cinematics"
generated_dir="Packages/TrinketContent/Sources/TrinketContent/Generated"
generated_swift="$generated_dir/UltimateCinematicCatalog.generated.swift"
state_file="$generated_dir/UltimateCinematicSourceHashes.generated.tsv"
combatants_tsv="ContentManifest/combatants.tsv"
hevc_preset="${CINEMATIC_HEVC_PRESET:-PresetHEVCHighestQuality}"

if [[ ! -f "$manifest" ]]; then
  echo "Missing manifest: $manifest" >&2
  exit 1
fi

if ! command -v avconvert >/dev/null 2>&1; then
  echo "Missing required tool: avconvert" >&2
  exit 1
fi

mkdir -p "$resources_dir" "$generated_dir"

entries_temp=$(mktemp)
seen_ids_temp=$(mktemp)
seen_assets_temp=$(mktemp)
active_assets_temp=$(mktemp)
processed_count=0
state_temp="$state_file.tmp.$$"
printf '%s\n' '# Generated by Scripts/prepare-cinematic-assets.sh. Do not edit directly.' > "$state_temp"
printf '%s\t%s\t%s\n' '# asset_name' 'source_sha256' 'encode_profile' >> "$state_temp"
generated_temp="$generated_swift.tmp.$$"
cleanup() {
  rm -f "$entries_temp" "$seen_ids_temp" "$seen_assets_temp" "$active_assets_temp" "$state_temp" "$state_temp.next" "$state_temp.sorted" "$generated_temp"
  rm -f "$resources_dir"/.*.tmp.$$.* 2>/dev/null || true
}
trap cleanup EXIT

trinket_asset_begin_state_lookup "$state_file"

# ISO BMFF sample entries use hvc1 (or hev1) for HEVC. Prefer this over mdls so CI
# does not depend on Spotlight indexing freshly written files.
assert_hevc_mp4() {
  local file="$1"
  if ! grep -a -q -E 'hvc1|hev1' "$file"; then
    echo "Expected HEVC (hvc1/hev1) in '$file'." >&2
    return 1
  fi
}

# Catalog ability ids are kebab-case; combatant ultimates columns use Swift symbols.
kebab_to_camel() {
  local kebab="$1"
  local result=""
  local part
  local first=1
  local IFS='-'
  # shellcheck disable=SC2086
  for part in $kebab; do
    if [[ $first -eq 1 ]]; then
      result="$part"
      first=0
    else
      result+="$(printf '%s' "${part:0:1}" | tr '[:lower:]' '[:upper:]')${part:1}"
    fi
  done
  printf '%s' "$result"
}

while IFS=$'\t' read -r actor_id ability_id asset_name source_path has_audio || [[ -n "${actor_id:-}" ]]; do
  [[ -z "${actor_id:-}" || "$actor_id" == \#* || "$actor_id" == "actor_id" ]] && continue

  if [[ -z "$asset_name" || -z "$source_path" || -z "$has_audio" ]]; then
    echo "Manifest row is missing required fields for actor_id '$actor_id' / ability_id '$ability_id'." >&2
    exit 1
  fi

  trinket_asset_validate_identifier "Actor id" "$actor_id"
  trinket_asset_validate_identifier "Ability id" "$ability_id"
  trinket_asset_validate_identifier "Asset name" "$asset_name"

  cast_key="$actor_id|$ability_id"

  trinket_asset_assert_unique "$seen_ids_temp" "cinematic cast key" "$cast_key"
  trinket_asset_assert_unique "$seen_assets_temp" "cinematic asset name" "$asset_name"

  if ! awk -F$'\t' -v id="$actor_id" 'NR > 1 && $1 == id && ($3 == "hero" || $3 == "companion") { found=1 } END { exit found ? 0 : 1 }' "$combatants_tsv"; then
    echo "Cinematic actor id '$actor_id' must match a Hero or Companion combatant." >&2
    exit 1
  fi

  if ! rg -Fq "id: \"$ability_id\"" \
    Packages/TrinketContent/Sources/TrinketContent/Content/AbilityCatalogUltimate.swift; then
    echo "Cinematic ability id '$ability_id' is not an Ultimate in the authored ability catalog." >&2
    exit 1
  fi

  ability_symbol="$(kebab_to_camel "$ability_id")"
  actor_ultimates="$(awk -F$'\t' -v id="$actor_id" 'NR > 1 && $1 == id { print $9; exit }' "$combatants_tsv")"
  if [[ -z "$actor_ultimates" ]]; then
    echo "Cinematic actor id '$actor_id' has no Ultimates column in $combatants_tsv." >&2
    exit 1
  fi
  case ",${actor_ultimates}," in
    *,"${ability_symbol}",*) ;;
    *)
      echo "Cinematic ability id '$ability_id' ($ability_symbol) is not an Ultimate for actor '$actor_id' (has: $actor_ultimates)." >&2
      exit 1
      ;;
  esac

  if [[ ! -f "$source_path" ]]; then
    echo "Missing source file for '$actor_id' / '$ability_id': $source_path" >&2
    exit 1
  fi

  case "$has_audio" in
    true|false) ;;
    *)
      echo "has_audio for '$actor_id' / '$ability_id' must be true or false." >&2
      exit 1
      ;;
  esac

  dest="$resources_dir/${asset_name}.mp4"
  source_hash="$(shasum -a 256 "$source_path" | awk '{print $1}')"
  trinket_asset_read_recorded_state recorded_hash recorded_profile "$asset_name"
  needs_convert=false
  if trinket_asset_needs_reencode "$recorded_hash" "$source_hash" "$recorded_profile" "$hevc_preset" "$dest"; then
    needs_convert=true
  fi

  if $needs_convert; then
    tmp_dest="$resources_dir/.${asset_name}.tmp.$$.mp4"
    rm -f "$tmp_dest"
    if ! avconvert \
      --source "$source_path" \
      --preset "$hevc_preset" \
      --output "$tmp_dest" \
      --replace \
      >/dev/null \
      || [[ ! -s "$tmp_dest" ]] \
      || ! assert_hevc_mp4 "$tmp_dest"; then
      rm -f "$tmp_dest"
      echo "Failed to encode cinematic asset for '$actor_id' / '$ability_id' with preset '$hevc_preset'." >&2
      exit 1
    fi
    mv -f "$tmp_dest" "$dest"
  fi
  printf '%s\t%s\t%s\n' "$asset_name" "$source_hash" "$hevc_preset" >> "$state_temp"
  printf '%s\n' "${asset_name}.mp4" >> "$active_assets_temp"

  escaped_cast_key="$(trinket_asset_escape_swift_string "$cast_key")"
  escaped_actor="$(trinket_asset_escape_swift_string "$actor_id")"
  escaped_ability="$(trinket_asset_escape_swift_string "$ability_id")"
  escaped_asset="$(trinket_asset_escape_swift_string "$asset_name")"

  cat >> "$entries_temp" <<SWIFT
        "$escaped_cast_key": UltimateCinematicReference(
            actorID: "$escaped_actor",
            abilityID: "$escaped_ability",
            videoName: "$escaped_asset",
            hasAudio: $has_audio
        ),
SWIFT
  processed_count=$((processed_count + 1))
done < "$manifest"

trinket_asset_prune_orphans "$resources_dir" "$active_assets_temp" "cinematic" "mp4"

cat > "$generated_temp" <<'SWIFT'
// Generated by Scripts/prepare-cinematic-assets.sh. Do not edit directly.

import Foundation

public struct UltimateCinematicReference: Equatable, Sendable {
    public let actorID: String
    public let abilityID: String
    public let videoName: String?
    public let hasAudio: Bool

    public static func fallback(actorID: String, abilityID: String) -> UltimateCinematicReference {
        UltimateCinematicReference(
            actorID: actorID,
            abilityID: abilityID,
            videoName: nil,
            hasAudio: false
        )
    }
}

public enum UltimateCinematicCatalog {
    public static let referencesByCastKey: [String: UltimateCinematicReference] = [
SWIFT

if [[ -s "$entries_temp" ]]; then
  cat "$entries_temp" >> "$generated_temp"
else
  echo "        // Add rows to CinematicManifest/cinematics.tsv when cinematic sources are ready." >> "$generated_temp"
fi

cat >> "$generated_temp" <<'SWIFT'
    ]

    public static func reference(for actorID: String, abilityID: String) -> UltimateCinematicReference {
        referencesByCastKey[castKey(actorID: actorID, abilityID: abilityID)]
            ?? .fallback(actorID: actorID, abilityID: abilityID)
    }

    public static func videoURL(for actorID: String, abilityID: String) -> URL? {
        let reference = reference(for: actorID, abilityID: abilityID)
        guard let videoName = reference.videoName else { return nil }
        return Bundle.main.url(forResource: videoName, withExtension: "mp4")
            ?? Bundle.main.url(forResource: videoName, withExtension: "mp4", subdirectory: "Media/Cinematics")
            ?? Bundle.main.url(forResource: videoName, withExtension: nil)
            ?? Bundle.main.url(forResource: videoName, withExtension: nil, subdirectory: "Media/Cinematics")
    }

    public static let allReferences: [UltimateCinematicReference] = Array(
        referencesByCastKey.values.sorted { $0.castKey < $1.castKey }
    )

    static func castKey(actorID: String, abilityID: String) -> String {
        "\(actorID)|\(abilityID)"
    }
}

private extension UltimateCinematicReference {
    var castKey: String {
        "\(actorID)|\(abilityID)"
    }
}
SWIFT

cmp -s "$generated_temp" "$generated_swift" 2>/dev/null || mv -f "$generated_temp" "$generated_swift"
rm -f "$entries_temp" "$seen_ids_temp" "$seen_assets_temp" "$active_assets_temp"
trinket_asset_sort_state "$state_temp" "$state_file"

echo "Prepared $processed_count cinematic asset(s)."
