#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

manifest="MusicManifest/music.tsv"
resources_dir="Trinket/Resources/Music"
generated_dir="Packages/TrinketContent/Sources/TrinketContent/Generated"
generated_swift="$generated_dir/MusicCatalog.generated.swift"
bitrate="${MUSIC_AAC_BITRATE:-96000}"

if [[ ! -f "$manifest" ]]; then
  echo "Missing manifest: $manifest" >&2
  exit 1
fi

if ! command -v afconvert >/dev/null 2>&1; then
  echo "Missing required tool: afconvert" >&2
  exit 1
fi

mkdir -p "$resources_dir" "$generated_dir"

tracks_temp=$(mktemp)
menu_temp=$(mktemp)
battle_temp=$(mktemp)
boss_temp=$(mktemp)
seen_ids_temp=$(mktemp)
seen_assets_temp=$(mktemp)
active_tracks_temp=$(mktemp)
processed_count=0

escape_swift_string() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

validate_identifier() {
  local label="$1" value="$2"
  if [[ ! "$value" =~ ^[A-Za-z0-9_][A-Za-z0-9_-]*$ ]]; then
    echo "$label '$value' should use letters, numbers, hyphens, or underscores, and start with a letter, number, or underscore." >&2
    exit 1
  fi
}

while IFS=$'\t' read -r kind id asset_name source_path boss_enemy_id looping volume_gain || [[ -n "${kind:-}" ]]; do
  [[ -z "${kind:-}" || "$kind" == \#* ]] && continue
  [[ "$boss_enemy_id" == "none" ]] && boss_enemy_id=""

  if [[ "$kind" != "menu" && "$kind" != "battle" && "$kind" != "boss" ]]; then
    echo "Unsupported music kind '$kind' for id '$id'." >&2
    exit 1
  fi

  if [[ -z "$id" || -z "$asset_name" || -z "$source_path" || -z "$looping" || -z "$volume_gain" ]]; then
    echo "Manifest row is missing required fields for id '$id'." >&2
    exit 1
  fi

  validate_identifier "Track id" "$id"
  validate_identifier "Asset name" "$asset_name"

  if grep -qx "$id" "$seen_ids_temp"; then
    echo "Duplicate music track id '$id'." >&2
    exit 1
  fi
  printf '%s\n' "$id" >> "$seen_ids_temp"

  if grep -qx "$asset_name" "$seen_assets_temp"; then
    echo "Duplicate music asset name '$asset_name'." >&2
    exit 1
  fi
  printf '%s\n' "$asset_name" >> "$seen_assets_temp"

  if [[ ! -f "$source_path" ]]; then
    echo "Missing source file for '$id': $source_path" >&2
    exit 1
  fi

  case "$looping" in
    true|false) ;;
    *)
      echo "Looping value for '$id' must be true or false." >&2
      exit 1
      ;;
  esac

  if [[ ! "$volume_gain" =~ ^[0-9]+([.][0-9]+)?$ ]]; then
    echo "Volume gain for '$id' must be numeric." >&2
    exit 1
  fi

  if [[ "$kind" == "boss" ]]; then
    if [[ -z "$boss_enemy_id" ]]; then
      echo "Boss music '$id' must include boss_enemy_id." >&2
      exit 1
    fi
    if ! grep -q "id: \"$boss_enemy_id\"" Packages/TrinketContent/Sources/TrinketContent/Generated/GameContentEnemies.generated.swift; then
      echo "Boss music '$id' references missing or non-boss enemy '$boss_enemy_id'." >&2
      exit 1
    fi
  elif [[ -n "$boss_enemy_id" ]]; then
    echo "Only boss music may include boss_enemy_id; '$id' has '$boss_enemy_id'." >&2
    exit 1
  fi

  # Track active assets for pruning
  printf '%s\n' "$asset_name.m4a" >> "$active_tracks_temp"

  output_file="$resources_dir/$asset_name.m4a"

  needs_convert=true
  if [[ -f "$output_file" && "$source_path" -ot "$output_file" ]]; then
    needs_convert=false
  fi

  if $needs_convert; then
    afconvert "$source_path" "$output_file" -f m4af -d aac -b "$bitrate" --soundcheck-generate >/dev/null
  fi

  escaped_id="$(escape_swift_string "$id")"
  escaped_asset="$(escape_swift_string "$asset_name")"
  escaped_boss="$(escape_swift_string "$boss_enemy_id")"

  cat >> "$tracks_temp" <<SWIFT
        MusicTrack(
            id: "$escaped_id",
            kind: .$kind,
            resourceName: "$escaped_asset",
            fileExtension: "m4a",
            bossEnemyID: "$escaped_boss",
            isLooping: $looping,
            volumeGain: $volume_gain
        ),
SWIFT

  case "$kind" in
    menu)
      cat >> "$menu_temp" <<SWIFT
        "$escaped_id",
SWIFT
      ;;
    battle)
      cat >> "$battle_temp" <<SWIFT
        "$escaped_id",
SWIFT
      ;;
    boss)
      cat >> "$boss_temp" <<SWIFT
        "$escaped_boss": "$escaped_id",
SWIFT
      ;;
  esac

  processed_count=$((processed_count + 1))
done < "$manifest"

cat > "$generated_swift" <<SWIFT
// Generated by Scripts/prepare-music-assets.sh. Do not edit directly.

import Foundation

public enum MusicCatalog {
    public static let allTracks: [MusicTrack] = [
$(cat "$tracks_temp")
    ]

    public static let menuTrackIDs: [String] = [
$(cat "$menu_temp")
    ]

    public static let battleTrackIDs: [String] = [
$(cat "$battle_temp")
    ]

    public static let bossTrackIDByEnemyID: [String: String] = [
$(cat "$boss_temp")
    ]
}
SWIFT

  # Prune orphaned music assets
  shopt -s nullglob
  for file in "$resources_dir"/*.m4a; do
    [[ -f "$file" ]] || continue
    filename=$(basename "$file")
    if ! grep -qx "$filename" "$active_tracks_temp"; then
      echo "Pruning orphaned music track: $filename"
      rm -f "$file"
    fi
  done
  shopt -u nullglob

rm -f "$tracks_temp" "$menu_temp" "$battle_temp" "$boss_temp" "$seen_ids_temp" "$seen_assets_temp" "$active_tracks_temp"

echo "Prepared $processed_count music assets in $resources_dir and regenerated $generated_swift."
