#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
# shellcheck source=lib/media-assets.sh
source "Scripts/lib/media-assets.sh"

manifest="ArtManifest/curated-assets.tsv"
asset_catalog="Trinket/Assets.xcassets"
generated_dir="Packages/TrinketContent/Sources/TrinketContent/Generated"
content_dir="Packages/TrinketContent/Sources/TrinketContent/Abilities"
generated_swift="$generated_dir/ArtCatalog.generated.swift"
source_hashes_file="$generated_dir/ArtSourceHashes.generated.tsv"

heic_quality="${ART_HEIC_QUALITY:-80}"
thumb_dimension="${ART_THUMB_DIMENSION:-480}"
portrait_thumb_dimension="${ART_PORTRAIT_THUMB_DIMENSION:-960}"
max_dimension_override="${ART_MAX_DIMENSION:-}"
combatant_dimension="${ART_COMBATANT_DIMENSION:-${max_dimension_override:-1320}}"
ability_dimension="${ART_ABILITY_DIMENSION:-${max_dimension_override:-960}}"
item_dimension="${ART_ITEM_DIMENSION:-${max_dimension_override:-960}}"
slot_background_dimension="${ART_SLOT_BACKGROUND_DIMENSION:-${max_dimension_override:-720}}"
background_dimension="${ART_BACKGROUND_DIMENSION:-${max_dimension_override:-1600}}"
portrait_background_dimension="${ART_PORTRAIT_BACKGROUND_DIMENSION:-${max_dimension_override:-2752}}"
encounter_dimension="${ART_ENCOUNTER_DIMENSION:-${max_dimension_override:-1320}}"
resource_dimension="${ART_RESOURCE_DIMENSION:-${max_dimension_override:-256}}"
talent_dimension="${ART_TALENT_DIMENSION:-${max_dimension_override:-960}}"

if [[ ! -f "$manifest" ]]; then
  echo "Missing manifest: $manifest" >&2
  exit 1
fi

mkdir -p "$asset_catalog" "$generated_dir"

scratch="$(mktemp -d)"
cleanup() {
  local status=$?
  rm -rf "$scratch"
  for backup in "$asset_catalog"/*.imageset.old.$$; do
    [[ -d "$backup" ]] || continue
    imageset="${backup%.old.$$}"
    if [[ ! -e "$imageset" ]]; then
      mv -f "$backup" "$imageset"
    else
      rm -rf "$backup"
    fi
  done
  rm -rf "$asset_catalog"/*.imageset.tmp.$$ 2>/dev/null || true
  return "$status"
}
trap cleanup EXIT

touch "$scratch"/{combatants,abilities,items,slot_backgrounds,backgrounds,portrait_backgrounds} \
  "$scratch"/{encounters,resources,talents,active_assets,seen_ids,seen_assets,prune_pairs}

printf '%s\n' "# Generated by Scripts/prepare-art-assets.sh. Do not edit directly." > "$scratch/source_hashes"
printf '%s\n' "# asset_name	source_sha256	encode_profile" >> "$scratch/source_hashes"
trinket_asset_begin_state_lookup "$source_hashes_file"

trinket_asset_extract_swift_quoted_ids "$scratch/combatant_ids" \
  "$generated_dir/GameContentRoster.generated.swift" \
  "$generated_dir/GameContentEnemies.generated.swift"
trinket_asset_extract_swift_quoted_ids "$scratch/ability_ids" \
  "$content_dir/AbilityCatalogBasic.swift" \
  "$content_dir/AbilityCatalogSkill.swift" \
  "$content_dir/AbilityCatalogUltimate.swift"
trinket_asset_extract_swift_quoted_ids "$scratch/item_ids" \
  "$generated_dir/GameContentItemBases.generated.swift"

awk -F'\t' '$1 == "combatant" {print $2}' "$manifest" | LC_ALL=C sort -u > "$scratch/manifest_combatant_ids"
awk -F'\t' '$1 == "ability" {print $2}' "$manifest" | LC_ALL=C sort -u > "$scratch/manifest_ability_ids"
awk -F'\t' '$1 == "item" {print $2}' "$manifest" | sed -e 's/-astral$//' -e 's/-basic$//' | LC_ALL=C sort -u > "$scratch/manifest_item_ids"

check_manifest_ids_present() {
  local wanted="$1" actual="$2" subject="$3" reason="$4"
  local missing missing_id
  missing=$(comm -23 "$wanted" "$actual")
  if [[ -n "$missing" ]]; then
    while IFS= read -r missing_id; do
      [[ -n "$missing_id" ]] || continue
      echo "$subject '$missing_id' $reason." >&2
    done <<< "$missing"
    exit 1
  fi
}

# Art IDs must be backed by the content owner that consumes them. This
# catches stale manifest rows before conversion creates orphaned assets.
check_manifest_ids_present "$scratch/manifest_combatant_ids" "$scratch/combatant_ids" \
  "Combatant art id" "is not present in the generated roster or enemy catalog"
check_manifest_ids_present "$scratch/manifest_ability_ids" "$scratch/ability_ids" \
  "Ability art id" "is not present in an authored ability catalog"
check_manifest_ids_present "$scratch/manifest_item_ids" "$scratch/item_ids" \
  "Item art id" "has no generated item base"


# Only rewrite when missing or content differs so no-op --assets runs do not
# invalidate actool.
cat > "$scratch/contents_json" <<'JSON'
{
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
JSON
trinket_asset_commit_generated "$scratch/contents_json" "$asset_catalog/Contents.json"


processed_count=0
full_count=0
thumb_count=0

heic_from_source() {
  local src="$1" dst="$2" sz="$3"
  sips -s format heic -s formatOptions "$heic_quality" -Z "$sz" "$src" --out "$dst" >/dev/null
  sips -d all "$dst" >/dev/null 2>&1 || true
}

write_imageset() {
  local imageset="$1"
  local asset_name="$2"
  local output_file="$3"
  local source_file="$4"
  local dimension="$5"

  local staged backup
  staged="${imageset}.tmp.$$"
  backup="${imageset}.old.$$"
  rm -rf "$staged" "$backup"
  mkdir -p "$staged"
  output_file="$staged/$(basename "$output_file")"
  heic_from_source "$source_file" "$output_file" "$dimension"
  [[ -s "$output_file" ]] || { rm -rf "$staged"; return 1; }
  cat > "$staged/Contents.json" <<JSON
{
  "images" : [
    {
      "filename" : "$asset_name.heic",
      "idiom" : "universal"
    }
  ],
  "info" : {
    "author" : "xcode",
    "version" : 1
  }
}
JSON
  if [[ -e "$imageset" ]]; then
    mv "$imageset" "$backup"
  fi
  if ! mv "$staged" "$imageset"; then
    [[ -e "$backup" ]] && mv "$backup" "$imageset"
    rm -rf "$staged"
    return 1
  fi
  rm -rf "$backup"
}

# Catalog usage drives which variants we ship:
# - every kind emits a full-size image
# - resource / slot_background: full only
# - combatant / ability / item / encounter / background: full + thumb
emit_thumb_for_kind() {
  case "$1" in
    resource|slot_background) return 1 ;;
    *) return 0 ;;
  esac
}

full_dimension_for_kind() {
  case "$1" in
    combatant) printf '%s\n' "$combatant_dimension" ;;
    ability) printf '%s\n' "$ability_dimension" ;;
    item) printf '%s\n' "$item_dimension" ;;
    slot_background) printf '%s\n' "$slot_background_dimension" ;;
    portrait_background) printf '%s\n' "$portrait_background_dimension" ;;
    background) printf '%s\n' "$background_dimension" ;;
    encounter) printf '%s\n' "$encounter_dimension" ;;
    resource) printf '%s\n' "$resource_dimension" ;;
    talent) printf '%s\n' "$talent_dimension" ;;
  esac
}

while IFS=$'\t' read -r kind id asset_name source_path focal_x focal_y || [[ -n "${kind:-}" ]]; do
  [[ -z "${kind:-}" || "$kind" == \#* ]] && continue

  if [[ "$kind" != "combatant" && "$kind" != "ability" && "$kind" != "item" && "$kind" != "slot_background" && "$kind" != "background" && "$kind" != "portrait_background" && "$kind" != "encounter" && "$kind" != "resource" && "$kind" != "talent" ]]; then
    echo "Unsupported art kind '$kind' for id '$id'." >&2
    exit 1
  fi

  if [[ -z "$id" || -z "$asset_name" || -z "$source_path" || -z "$focal_x" || -z "$focal_y" ]]; then
    echo "Manifest row is missing required fields for id '$id'." >&2
    exit 1
  fi

  trinket_asset_assert_unique "$scratch/seen_ids" "art id '$id' for kind '$kind'" "$kind:$id"
  if [[ ! "$asset_name" =~ ^[A-Za-z0-9_]+$ ]]; then
    echo "Asset name '$asset_name' should use only letters, numbers, and underscores." >&2
    exit 1
  fi
  trinket_asset_assert_unique "$scratch/seen_assets" "art asset name" "$asset_name"

  if [[ ! "$focal_x" =~ ^[0-9]+([.][0-9]+)?$ || ! "$focal_y" =~ ^[0-9]+([.][0-9]+)?$ ]] \
    || ! awk -v x="$focal_x" -v y="$focal_y" 'BEGIN { exit !(x >= 0 && x <= 1 && y >= 0 && y <= 1) }'; then
    echo "Focal values for '$id' must be numeric values between 0 and 1." >&2
    exit 1
  fi

  # Row-local allowlists stay per-row; cross-manifest id backing was
  # pre-validated in bulk above.
  case "$kind" in
    talent)
      case "$id" in
        physical|burn|stun|block|health|gold|holy|poison|bleed|leech|freeze|dodge|purge|cleanse|mana|deathsDoor) ;;
        *)
          echo "Talent art id '$id' is not a valid Keyword case." >&2
          exit 1
          ;;
      esac
      ;;
  esac

  want_full=true
  want_thumb=false
  if emit_thumb_for_kind "$kind"; then
    want_thumb=true
  fi
  full_dimension="$(full_dimension_for_kind "$kind")"
  selected_thumb_dimension="$thumb_dimension"
  [[ "$kind" != "portrait_background" ]] || selected_thumb_dimension="$portrait_thumb_dimension"

  imageset="$asset_catalog/$asset_name.imageset"
  output_file="$imageset/$asset_name.heic"
  thumb_asset="${asset_name}_thumb"
  thumb_imageset="$asset_catalog/${thumb_asset}.imageset"
  thumb_output_file="$thumb_imageset/${thumb_asset}.heic"

  if $want_full; then
    printf '%s\n' "$asset_name" >> "$scratch/active_assets"
  fi
  if $want_thumb; then
    printf '%s\n' "$thumb_asset" >> "$scratch/active_assets"
  fi

  source_file="$source_path"
  if [[ ! -f "$source_file" ]]; then
    echo "Missing source file for '$id': $source_path" >&2
    exit 1
  fi

  source_file_hash="$(shasum -a 256 "$source_file" | awk '{print $1}')"
  # Output settings participate in invalidation so sizing-only pipeline changes
  # cannot silently leave stale oversized assets in the catalog.
  encode_profile="q${heic_quality}/full${full_dimension}/thumb${selected_thumb_dimension}/thumb:${want_thumb}"
  source_hash="$(printf '%s\t%s\t%s\t%s\t%s\n' \
    "$source_file_hash" "$heic_quality" "$full_dimension" "$selected_thumb_dimension" "$want_thumb" \
    | shasum -a 256 | awk '{print $1}')"
  trinket_asset_read_recorded_state recorded_hash recorded_profile "$asset_name"
  printf '%s\t%s\t%s\n' "$asset_name" "$source_hash" "$encode_profile" >> "$scratch/source_hashes"

  needs_convert=false
  if [[ "${FORCE_ASSET_REENCODE:-0}" == "1" ]]; then
    needs_convert=true
  elif [[ -z "$recorded_hash" || "$recorded_hash" != "$source_hash" ]]; then
    needs_convert=true
  else
    if $want_full && [[ ! -f "$output_file" ]]; then
      needs_convert=true
    fi
    if $want_thumb && [[ ! -f "$thumb_output_file" ]]; then
      needs_convert=true
    fi
  fi

  if $needs_convert; then
    if $want_full; then
      write_imageset "$imageset" "$asset_name" "$output_file" "$source_file" "$full_dimension"
      full_count=$((full_count + 1))
    fi
    if $want_thumb; then
      write_imageset "$thumb_imageset" "$thumb_asset" "$thumb_output_file" "$source_file" "$selected_thumb_dimension"
      thumb_count=$((thumb_count + 1))
    fi
  fi

  # Remove the variant we no longer ship for this kind.
  if ! $want_full && [[ -d "$imageset" ]]; then
    rm -rf "$imageset"
  fi
  if ! $want_thumb && [[ -d "$thumb_imageset" ]]; then
    rm -rf "$thumb_imageset"
  fi

  if [[ "$kind" == "background" || "$kind" == "portrait_background" ]]; then
    source_aspect_ratio="$(sips -g pixelWidth -g pixelHeight "$output_file" | awk '/pixelWidth:/{w=$2} /pixelHeight:/{h=$2} END {printf "%.12f", w/h}')"
    if [[ ! "$source_aspect_ratio" =~ ^[0-9]+\.[0-9]+$ ]]; then
      echo "Could not determine aspect ratio for '$id' from '$output_file'." >&2
      exit 1
    fi
  fi

  escaped_id="$(trinket_asset_escape_swift_string "$id")"
  escaped_asset="$(trinket_asset_escape_swift_string "$asset_name")"
  escaped_thumb="$(trinket_asset_escape_swift_string "$thumb_asset")"
  if [[ "$kind" == "combatant" ]]; then
    cat >> "$scratch/combatants" <<SWIFT
        dict["$escaped_id"] = CombatantArtReference(
            imageName: "$escaped_asset",
            thumbnailImageName: "$escaped_thumb",
            focalPoint: ArtFocalPoint(x: $focal_x, y: $focal_y)
        )
SWIFT
  elif [[ "$kind" == "ability" ]]; then
    cat >> "$scratch/abilities" <<SWIFT
        dict["$escaped_id"] = AbilityArtReference(
            imageName: "$escaped_asset",
            thumbnailImageName: "$escaped_thumb"
        )
SWIFT
  elif [[ "$kind" == "item" ]]; then
    cat >> "$scratch/items" <<SWIFT
        dict["$escaped_id"] = ItemArtReference(
            imageName: "$escaped_asset",
            thumbnailImageName: "$escaped_thumb"
        )
SWIFT
  elif [[ "$kind" == "slot_background" ]]; then
    case "$id" in
      weapon|armor|accessory|trinket) ;;
      *)
        echo "Slot background id '$id' must be one of: weapon, armor, accessory, trinket." >&2
        exit 1
        ;;
    esac
    cat >> "$scratch/slot_backgrounds" <<SWIFT
        dict[.$id] = SlotBackgroundArtReference(
            imageName: "$escaped_asset"
        )
SWIFT
  elif [[ "$kind" == "background" ]]; then
    cat >> "$scratch/backgrounds" <<SWIFT
        dict["$escaped_id"] = BackgroundArtReference(
            imageName: "$escaped_asset",
            thumbnailImageName: "$escaped_thumb",
            sourceAspectRatio: $source_aspect_ratio,
            focalPoint: ArtFocalPoint(x: $focal_x, y: $focal_y)
        )
SWIFT
  elif [[ "$kind" == "portrait_background" ]]; then
    cat >> "$scratch/portrait_backgrounds" <<SWIFT
        dict["$escaped_id"] = BackgroundArtReference(
            imageName: "$escaped_asset",
            thumbnailImageName: "$escaped_thumb",
            sourceAspectRatio: $source_aspect_ratio,
            focalPoint: ArtFocalPoint(x: $focal_x, y: $focal_y)
        )
SWIFT
  elif [[ "$kind" == "resource" ]]; then
    cat >> "$scratch/resources" <<SWIFT
        dict["$escaped_id"] = ResourceArtReference(
            imageName: "$escaped_asset"
        )
SWIFT
  elif [[ "$kind" == "encounter" ]]; then
    cat >> "$scratch/encounters" <<SWIFT
        dict["$escaped_id"] = EncounterArtReference(
            imageName: "$escaped_asset",
            thumbnailImageName: "$escaped_thumb"
        )
SWIFT
  elif [[ "$kind" == "talent" ]]; then
    cat >> "$scratch/talents" <<SWIFT
        dict[.$id] = TalentArtReference(
            imageName: "$escaped_asset",
            thumbnailImageName: "$escaped_thumb"
        )
SWIFT
  fi

  processed_count=$((processed_count + 1))
done < "$manifest"

{
  cat <<'SWIFT_HEADER'
// Generated by Scripts/prepare-art-assets.sh. Do not edit directly.

import TrinketCore

/// Normalized art crop anchor. Kept as Doubles so the catalog stays Sendable
/// without relying on SwiftUI `UnitPoint` Sendable conformance.
public struct ArtFocalPoint: Hashable, Sendable {
    public let x: Double
    public let y: Double

    public init(x: Double, y: Double) {
        self.x = x
        self.y = y
    }
}
SWIFT_HEADER

  cat <<SWIFT

public struct CombatantArtReference: Hashable, Sendable {
    public let imageName: String
    public let thumbnailImageName: String?
    public let focalPoint: ArtFocalPoint
}

public struct AbilityArtReference: Hashable, Sendable {
    public let imageName: String
    public let thumbnailImageName: String?
}

public struct ItemArtReference: Hashable, Sendable {
    public let imageName: String
    public let thumbnailImageName: String?
}

public struct SlotBackgroundArtReference: Hashable, Sendable {
    public let imageName: String
}

public struct BackgroundArtReference: Hashable, Sendable {
    public let imageName: String
    public let thumbnailImageName: String?
    public let sourceAspectRatio: Double
    public let focalPoint: ArtFocalPoint
}

public struct ResourceArtReference: Hashable, Sendable {
    public let imageName: String
}

public struct EncounterArtReference: Hashable, Sendable {
    public let imageName: String
    public let thumbnailImageName: String?
}

public struct TalentArtReference: Hashable, Sendable {
    public let imageName: String
    public let thumbnailImageName: String?
}


public enum ArtCatalog {
    public static let combatantArtByID: [String: CombatantArtReference] = {
        var dict = [String: CombatantArtReference]()
$(cat "$scratch/combatants")
        return dict
    }()

    public static let abilityArtByID: [String: AbilityArtReference] = {
        var dict = [String: AbilityArtReference]()
$(cat "$scratch/abilities")
        return dict
    }()

    public static let itemArtByID: [String: ItemArtReference] = {
        var dict = [String: ItemArtReference]()
$(cat "$scratch/items")
        return dict
    }()

    public static let slotBackgroundArtByID: [ItemSlot: SlotBackgroundArtReference] = {
        var dict = [ItemSlot: SlotBackgroundArtReference]()
$(cat "$scratch/slot_backgrounds")
        return dict
    }()

    public static let backgroundArtByID: [String: BackgroundArtReference] = {
        var dict = [String: BackgroundArtReference]()
$(cat "$scratch/backgrounds")
        return dict
    }()

    public static let portraitBackgroundArtByID: [String: BackgroundArtReference] = {
        var dict = [String: BackgroundArtReference]()
$(cat "$scratch/portrait_backgrounds")
        return dict
    }()

    public static let encounterArtByID: [String: EncounterArtReference] = {
        var dict = [String: EncounterArtReference]()
$(cat "$scratch/encounters")
        return dict
    }()

    public static let resourceArtByID: [String: ResourceArtReference] = {
        var dict = [String: ResourceArtReference]()
$(cat "$scratch/resources")
        return dict
    }()

    public static let talentArtByID: [Keyword: TalentArtReference] = {
        var dict = [Keyword: TalentArtReference]()
$(cat "$scratch/talents")
        return dict
    }()

}

extension Combatant {
    public var artReference: CombatantArtReference? {
        ArtCatalog.combatantArtByID[id]
    }
}

extension Ability {
    public var artReference: AbilityArtReference? {
        ArtCatalog.abilityArtByID[id]
    }
}

extension Keyword {
    public var artReference: TalentArtReference? {
        ArtCatalog.talentArtByID[self]
    }
}

SWIFT

  # Quoted heredoc so Swift interpolations and comments are not shell-expanded.
  cat <<'SWIFT_EXTENSIONS'
extension InventoryItem {
    public var artReference: ItemArtReference? {
        // Catalog keys are template ids (e.g. crossbow-basic), not per-instance ids.
        ArtCatalog.itemArtByID[templateID]
            ?? ArtCatalog.itemArtByID["\(baseType.id)-\(rarity.rawValue)"]
            ?? baseType.previewArtReference
    }
}

extension ItemSlot {
    public var slotBackgroundReference: SlotBackgroundArtReference? {
        ArtCatalog.slotBackgroundArtByID[self]
    }
}

public extension ArtCatalog {
    static let allImageNames: [String] = {
        var names = Set<String>()
        for reference in combatantArtByID.values {
            names.insert(reference.imageName)
            if let thumb = reference.thumbnailImageName { names.insert(thumb) }
        }
        for reference in abilityArtByID.values {
            names.insert(reference.imageName)
            if let thumb = reference.thumbnailImageName { names.insert(thumb) }
        }
        for reference in itemArtByID.values {
            names.insert(reference.imageName)
            if let thumb = reference.thumbnailImageName { names.insert(thumb) }
        }
        for reference in slotBackgroundArtByID.values {
            names.insert(reference.imageName)
        }
        for reference in backgroundArtByID.values {
            names.insert(reference.imageName)
            if let thumb = reference.thumbnailImageName { names.insert(thumb) }
        }
        for reference in portraitBackgroundArtByID.values {
            names.insert(reference.imageName)
            if let thumb = reference.thumbnailImageName { names.insert(thumb) }
        }
        for reference in encounterArtByID.values {
            names.insert(reference.imageName)
            if let thumb = reference.thumbnailImageName { names.insert(thumb) }
        }
        for reference in resourceArtByID.values {
            names.insert(reference.imageName)
        }
        for reference in talentArtByID.values {
            names.insert(reference.imageName)
            if let thumb = reference.thumbnailImageName { names.insert(thumb) }
        }
        return names.sorted()
    }()

    static let allImageNamesSet: Set<String> = Set(allImageNames)
}
SWIFT_EXTENSIONS
} > "$scratch/generated"

trinket_asset_commit_generated "$scratch/generated" "$generated_swift"

trinket_asset_sort_state "$scratch/source_hashes" "$source_hashes_file"

# Prune orphaned assets with one bulk membership check instead of a grep
# per directory. Any imageset outside the active set goes, matching the
# orphan rule in check-unused-assets.py (accent/app-icon sets never match
# *.imageset, so they are unaffected).
shopt -s nullglob
for dir in "$asset_catalog"/*/*.imageset "$asset_catalog"/*.imageset; do
  [[ -d "$dir" ]] || continue
  foldername=$(basename "$dir")
  name="${foldername%.imageset}"
  printf '%s\t%s\n' "$name" "$dir" >> "$scratch/prune_pairs"
done
shopt -u nullglob
LC_ALL=C sort -t$'\t' -k1,1 -o "$scratch/prune_pairs" "$scratch/prune_pairs"
LC_ALL=C sort -u -o "$scratch/active_assets" "$scratch/active_assets"
while IFS=$'\t' read -r name dir; do
  [[ -n "${name:-}" && -n "${dir:-}" ]] || continue
  echo "Pruning orphaned asset: $(basename "$dir")"
  rm -rf "$dir"
done < <(join -t$'\t' -v 1 -1 1 -2 1 "$scratch/prune_pairs" "$scratch/active_assets")


echo "Prepared $processed_count curated art asset(s) (converted $full_count full / $thumb_count thumb this run; kind-aware variants)."
