#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

manifest="CinematicManifest/cinematics.tsv"
resources_dir="Trinket/Resources/Cinematics"
generated_dir="Packages/TrinketContent/Sources/TrinketContent/Generated"
generated_swift="$generated_dir/UltimateCinematicCatalog.generated.swift"

if [[ ! -f "$manifest" ]]; then
  echo "Missing manifest: $manifest" >&2
  exit 1
fi

mkdir -p "$resources_dir" "$generated_dir"

entries_temp=$(mktemp)
seen_ids_temp=$(mktemp)
seen_assets_temp=$(mktemp)
active_assets_temp=$(mktemp)
processed_count=0

escape_swift_string() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

validate_identifier() {
  local label="$1" value="$2"
  # Intentionally unquoted: bash treats a quoted =~ RHS as a literal string.
  if [[ ! "$value" =~ ^[A-Za-z0-9_][A-Za-z0-9_-]*$ ]]; then
    echo "$label '$value' should use letters, numbers, hyphens, or underscores, and start with a letter, number, or underscore." >&2
    exit 1
  fi
}

while IFS=$'\t' read -r ability_id asset_name source_path has_audio display_aspect_w display_aspect_h || [[ -n "${ability_id:-}" ]]; do
  [[ -z "${ability_id:-}" || "$ability_id" == \#* || "$ability_id" == "ability_id" ]] && continue

  if [[ -z "$asset_name" || -z "$source_path" || -z "$has_audio" || -z "$display_aspect_w" || -z "$display_aspect_h" ]]; then
    echo "Manifest row is missing required fields for ability_id '$ability_id'." >&2
    exit 1
  fi

  validate_identifier "Ability id" "$ability_id"
  validate_identifier "Asset name" "$asset_name"

  if grep -qx "$ability_id" "$seen_ids_temp"; then
    echo "Duplicate cinematic ability id '$ability_id'." >&2
    exit 1
  fi
  printf '%s\n' "$ability_id" >> "$seen_ids_temp"

  if grep -qx "$asset_name" "$seen_assets_temp"; then
    echo "Duplicate cinematic asset name '$asset_name'." >&2
    exit 1
  fi
  printf '%s\n' "$asset_name" >> "$seen_assets_temp"

  if [[ ! -f "$source_path" ]]; then
    echo "Missing source file for '$ability_id': $source_path" >&2
    exit 1
  fi

  case "$has_audio" in
    true|false) ;;
    *)
      echo "has_audio for '$ability_id' must be true or false." >&2
      exit 1
      ;;
  esac

  if [[ ! "$display_aspect_w" =~ ^[0-9]+$ || ! "$display_aspect_h" =~ ^[0-9]+$ ]]; then
    echo "Display aspect for '$ability_id' must be integer width and height." >&2
    exit 1
  fi

  dest="$resources_dir/${asset_name}.mp4"
  if [[ ! -f "$dest" || "$source_path" -nt "$dest" ]]; then
    cp "$source_path" "$dest"
  fi
  printf '%s\n' "${asset_name}.mp4" >> "$active_assets_temp"

  escaped_id="$(escape_swift_string "$ability_id")"
  escaped_asset="$(escape_swift_string "$asset_name")"

  cat >> "$entries_temp" <<SWIFT
        "$escaped_id": UltimateCinematicReference(
            abilityID: "$escaped_id",
            videoName: "$escaped_asset",
            hasAudio: $has_audio,
            displayAspectWidth: $display_aspect_w,
            displayAspectHeight: $display_aspect_h
        ),
SWIFT
  processed_count=$((processed_count + 1))
done < "$manifest"

# Remove stale generated videos that are no longer in the manifest.
shopt -s nullglob
for existing in "$resources_dir"/*.mp4; do
  base="$(basename "$existing")"
  if ! grep -qx "$base" "$active_assets_temp"; then
    rm -f "$existing"
  fi
done
shopt -u nullglob

cat > "$generated_swift" <<'SWIFT'
// Generated by Scripts/prepare-cinematic-assets.sh. Do not edit directly.

import Foundation

public struct UltimateCinematicReference: Equatable, Sendable {
    public let abilityID: String
    public let videoName: String?
    public let hasAudio: Bool
    /// Battle always presents cinematics in 9:16; sources may differ and are cropped.
    public let displayAspectWidth: Int
    public let displayAspectHeight: Int

    public static func fallback(abilityID: String) -> UltimateCinematicReference {
        UltimateCinematicReference(
            abilityID: abilityID,
            videoName: nil,
            hasAudio: false,
            displayAspectWidth: 9,
            displayAspectHeight: 16
        )
    }
}

public enum UltimateCinematicCatalog {
    public static let referencesByAbilityID: [String: UltimateCinematicReference] = [
SWIFT

if [[ -s "$entries_temp" ]]; then
  cat "$entries_temp" >> "$generated_swift"
else
  echo "        // Add rows to CinematicManifest/cinematics.tsv when cinematic sources are ready." >> "$generated_swift"
fi

cat >> "$generated_swift" <<'SWIFT'
    ]

    public static func reference(for abilityID: String) -> UltimateCinematicReference {
        referencesByAbilityID[abilityID] ?? .fallback(abilityID: abilityID)
    }

    public static func videoURL(for abilityID: String) -> URL? {
        let reference = reference(for: abilityID)
        guard let videoName = reference.videoName else { return nil }
        return Bundle.main.url(forResource: videoName, withExtension: "mp4")
            ?? Bundle.main.url(forResource: videoName, withExtension: nil)
    }
}
SWIFT

rm -f "$entries_temp" "$seen_ids_temp" "$seen_assets_temp" "$active_assets_temp"

echo "Prepared $processed_count cinematic asset(s)."
