#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

manifest="CinematicManifest/cinematics.tsv"
resources_dir="Trinket/Resources/Cinematics"
generated_dir="Packages/TrinketContent/Sources/TrinketContent/Generated"
generated_swift="$generated_dir/UltimateCinematicCatalog.generated.swift"
state_file="$generated_dir/UltimateCinematicSourceHashes.generated.tsv"

if [[ ! -f "$manifest" ]]; then
  echo "Missing manifest: $manifest" >&2
  exit 1
fi

mkdir -p "$resources_dir" "$generated_dir"

entries_temp=$(mktemp)
seen_ids_temp=$(mktemp)
seen_assets_temp=$(mktemp)
active_assets_temp=$(mktemp)
processed_count=0
state_temp="$state_file.tmp.$$"
state_was_present=false
if [[ -f "$state_file" ]]; then
  cp "$state_file" "$state_temp"
  state_was_present=true
else
  printf '%s\n' '# Generated by Scripts/prepare-cinematic-assets.sh. Do not edit directly.' > "$state_temp"
  printf '%s\t%s\n' '# asset_name' 'source_sha256' >> "$state_temp"
fi
generated_temp="$generated_swift.tmp.$$"
cleanup() {
  rm -f "$entries_temp" "$seen_ids_temp" "$seen_assets_temp" "$active_assets_temp" "$state_temp" "$state_temp.next" "$state_temp.sorted" "$generated_temp"
  rm -f "$resources_dir"/.*.tmp.$$.* 2>/dev/null || true
}
trap cleanup EXIT

escape_swift_string() {
  printf '%s' "$1" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

validate_identifier() {
  local label="$1" value="$2"
  # Intentionally unquoted: bash treats a quoted =~ RHS as a literal string.
  if [[ ! "$value" =~ ^[A-Za-z0-9_][A-Za-z0-9_-]*$ ]]; then
    echo "$label '$value' should use letters, numbers, hyphens, or underscores, and start with a letter, number, or underscore." >&2
    exit 1
  fi
}

while IFS=$'\t' read -r ability_id asset_name source_path has_audio display_aspect_w display_aspect_h || [[ -n "${ability_id:-}" ]]; do
  [[ -z "${ability_id:-}" || "$ability_id" == \#* || "$ability_id" == "ability_id" ]] && continue

  if [[ -z "$asset_name" || -z "$source_path" || -z "$has_audio" || -z "$display_aspect_w" || -z "$display_aspect_h" ]]; then
    echo "Manifest row is missing required fields for ability_id '$ability_id'." >&2
    exit 1
  fi

  validate_identifier "Ability id" "$ability_id"
  validate_identifier "Asset name" "$asset_name"

  if grep -qx "$ability_id" "$seen_ids_temp"; then
    echo "Duplicate cinematic ability id '$ability_id'." >&2
    exit 1
  fi
  printf '%s\n' "$ability_id" >> "$seen_ids_temp"

  if grep -qx "$asset_name" "$seen_assets_temp"; then
    echo "Duplicate cinematic asset name '$asset_name'." >&2
    exit 1
  fi
  printf '%s\n' "$asset_name" >> "$seen_assets_temp"

  if [[ ! -f "$source_path" ]]; then
    echo "Missing source file for '$ability_id': $source_path" >&2
    exit 1
  fi

  case "$has_audio" in
    true|false) ;;
    *)
      echo "has_audio for '$ability_id' must be true or false." >&2
      exit 1
      ;;
  esac

  if [[ ! "$display_aspect_w" =~ ^[0-9]+$ || ! "$display_aspect_h" =~ ^[0-9]+$ ]]; then
    echo "Display aspect for '$ability_id' must be integer width and height." >&2
    exit 1
  fi
  if (( display_aspect_w <= 0 || display_aspect_h <= 0 )); then
    echo "Display aspect for '$ability_id' must be greater than zero." >&2
    exit 1
  fi

  if ! rg -Fq "id: \"$ability_id\"" \
    Packages/TrinketContent/Sources/TrinketContent/Content/AbilityCatalogBasic.swift \
    Packages/TrinketContent/Sources/TrinketContent/Content/AbilityCatalogSkill.swift \
    Packages/TrinketContent/Sources/TrinketContent/Content/AbilityCatalogUltimate.swift; then
    echo "Cinematic ability id '$ability_id' is not present in an authored ability catalog." >&2
    exit 1
  fi

  dest="$resources_dir/${asset_name}.mp4"
  source_hash="$(shasum -a 256 "$source_path" | awk '{print $1}')"
  recorded_hash="$(awk -F$'\t' -v name="$asset_name" '$1 == name { print $2; exit }' "$state_file" 2>/dev/null || true)"
  if [[ "${FORCE_ASSET_REENCODE:-0}" == "1" \
    || ! -f "$dest" \
    || ( "$state_was_present" == true && "$recorded_hash" != "$source_hash" ) ]]; then
    tmp_dest="$resources_dir/.${asset_name}.tmp.$$.mp4"
    rm -f "$tmp_dest"
    if ! cp "$source_path" "$tmp_dest" || [[ ! -s "$tmp_dest" ]]; then
      rm -f "$tmp_dest"
      echo "Failed to stage cinematic asset for '$ability_id'." >&2
      exit 1
    fi
    mv -f "$tmp_dest" "$dest"
  fi
  awk -F$'\t' -v name="$asset_name" '$1 != name { print }' "$state_temp" > "$state_temp.next"
  printf '%s\t%s\n' "$asset_name" "$source_hash" >> "$state_temp.next"
  mv -f "$state_temp.next" "$state_temp"
  printf '%s\n' "${asset_name}.mp4" >> "$active_assets_temp"

  escaped_id="$(escape_swift_string "$ability_id")"
  escaped_asset="$(escape_swift_string "$asset_name")"

  cat >> "$entries_temp" <<SWIFT
        "$escaped_id": UltimateCinematicReference(
            abilityID: "$escaped_id",
            videoName: "$escaped_asset",
            hasAudio: $has_audio,
            displayAspectWidth: $display_aspect_w,
            displayAspectHeight: $display_aspect_h
        ),
SWIFT
  processed_count=$((processed_count + 1))
done < "$manifest"

# Remove stale generated videos that are no longer in the manifest.
shopt -s nullglob
for existing in "$resources_dir"/*.mp4; do
  base="$(basename "$existing")"
  if ! grep -qx "$base" "$active_assets_temp"; then
    rm -f "$existing"
  fi
done
shopt -u nullglob

cat > "$generated_temp" <<'SWIFT'
// Generated by Scripts/prepare-cinematic-assets.sh. Do not edit directly.

import Foundation

public struct UltimateCinematicReference: Equatable, Sendable {
    public let abilityID: String
    public let videoName: String?
    public let hasAudio: Bool
    /// Battle always presents cinematics in 9:16; sources may differ and are cropped.
    public let displayAspectWidth: Int
    public let displayAspectHeight: Int

    public static func fallback(abilityID: String) -> UltimateCinematicReference {
        UltimateCinematicReference(
            abilityID: abilityID,
            videoName: nil,
            hasAudio: false,
            displayAspectWidth: 9,
            displayAspectHeight: 16
        )
    }
}

public enum UltimateCinematicCatalog {
    public static let referencesByAbilityID: [String: UltimateCinematicReference] = [
SWIFT

if [[ -s "$entries_temp" ]]; then
  cat "$entries_temp" >> "$generated_temp"
else
  echo "        // Add rows to CinematicManifest/cinematics.tsv when cinematic sources are ready." >> "$generated_temp"
fi

cat >> "$generated_temp" <<'SWIFT'
    ]

    public static func reference(for abilityID: String) -> UltimateCinematicReference {
        referencesByAbilityID[abilityID] ?? .fallback(abilityID: abilityID)
    }

    public static func videoURL(for abilityID: String) -> URL? {
        let reference = reference(for: abilityID)
        guard let videoName = reference.videoName else { return nil }
        return Bundle.main.url(forResource: videoName, withExtension: "mp4")
            ?? Bundle.main.url(forResource: videoName, withExtension: nil)
    }
}
SWIFT

cmp -s "$generated_temp" "$generated_swift" 2>/dev/null || mv -f "$generated_temp" "$generated_swift"
rm -f "$entries_temp" "$seen_ids_temp" "$seen_assets_temp" "$active_assets_temp"
{
  head -n 2 "$state_temp"
  tail -n +3 "$state_temp" | LC_ALL=C sort -t$'\t' -k1,1
} > "$state_temp.sorted"
mv -f "$state_temp.sorted" "$state_temp"
mv -f "$state_temp" "$state_file"

echo "Prepared $processed_count cinematic asset(s)."
