name: Trinket PR

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: pr-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    with:
      artifact-prefix: pr-
      include-exhaustive: true
